from django.db import models


class SatScanCluster(models.Model):
    year_month = models.TextField(null=True,blank=True,default=None)
    lab = models.TextField(null=True,blank=True,default=None)
    cluster_number = models.TextField(null=True,blank=True,default=None)
    cluster_code = models.TextField(null=True,blank=True,default=None)
    cluster_description = models.TextField(null=True,blank=True,default=None)
    cluster_start_date = models.DateField(null=True,blank=True,default=None)
    cluster_end_date = models.DateField(null=True,blank=True,default=None)
    date_first_signal = models.DateField(null=True,blank=True,default=None)
    date_last_signal = models.DateField(null=True,blank=True,default=None)
    recurrence_interval = models.TextField(null=True,blank=True,default=None)
    recurrence_highest = models.TextField(null=True,blank=True,default=None)
    recurrence_final = models.TextField(null=True,blank=True,default=None)
    p_value_first = models.TextField(null=True,blank=True,default=None)
    p_value_lowest = models.TextField(null=True,blank=True,default=None)
    p_value_final = models.TextField(null=True,blank=True,default=None)
    number_observed_first = models.TextField(null=True,blank=True,default=None)
    number_observed_max = models.TextField(null=True,blank=True,default=None)
    number_observed_final = models.TextField(null=True,blank=True,default=None)
    number_observed_total = models.TextField(null=True,blank=True,default=None)
    number_expected_first = models.TextField(null=True,blank=True,default=None)
    number_expected_max = models.TextField(null=True,blank=True,default=None)
    number_expected_final = models.TextField(null=True,blank=True,default=None)
    days_to_first_signal = models.TextField(null=True,blank=True,default=None)
    total_days_cluster = models.TextField(null=True,blank=True,default=None)
    number_of_signals = models.TextField(null=True,blank=True,default=None)
    number_of_locations = models.TextField(null=True,blank=True,default=None)
    radius = models.TextField(null=True,blank=True,default=None)
    satscan_x = models.TextField(null=True,blank=True,default=None)
    satscan_y = models.TextField(null=True,blank=True,default=None)
    january = models.TextField(null=True,blank=True,default=None)
    february = models.TextField(null=True,blank=True,default=None)
    march = models.TextField(null=True,blank=True,default=None)
    april = models.TextField(null=True,blank=True,default=None)
    may = models.TextField(null=True,blank=True,default=None)
    june = models.TextField(null=True,blank=True,default=None)
    july = models.TextField(null=True,blank=True,default=None)
    august = models.TextField(null=True,blank=True,default=None)
    september = models.TextField(null=True,blank=True,default=None)
    october = models.TextField(null=True,blank=True,default=None)
    november = models.TextField(null=True,blank=True,default=None)
    december = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    
    


class SatScanPatientList(models.Model):
    year_month = models.TextField(null=True,blank=True,default=None)
    cluster_number = models.TextField(null=True,blank=True,default=None)
    lab = models.TextField(null=True,blank=True,default=None)
    identification_number = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_of_birth = models.TextField(null=True,blank=True,default=None)
    age_group = models.TextField(null=True,blank=True,default=None)
    location = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    location_type = models.TextField(null=True,blank=True,default=None)
    specimen_number = models.TextField(null=True,blank=True,default=None)
    specimen_date = models.DateField(null=True,blank=True,default=None)
    specimen_type = models.TextField(null=True,blank=True,default=None)
    organism = models.TextField(null=True,blank=True,default=None)
    beta_lactamase = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    referral_isolates = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    icr = models.TextField(null=True,blank=True,default=None)
    meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    carb = models.TextField(null=True,blank=True,default=None)
    date_of_admission = models.DateField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    urine_colony = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)





class RawFileName(models.Model):
    file_name = models.TextField(null=True,blank=True,default=None,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_name
    

class RawOrigin(models.Model):
    file_ref = models.ForeignKey(RawFileName, on_delete=models.CASCADE)
    country_a = models.TextField(null=True,blank=True,default=None)
    region = models.TextField(null=True,blank=True,default=None)
    island = models.TextField(null=True,blank=True,default=None)
    laboratory = models.TextField(null=True,blank=True,default=None)
    patient_id = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    mid_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_birth = models.TextField(null=True,blank=True,default=None)
    age_grp = models.TextField(null=True,blank=True,default=None)
    pat_type = models.TextField(null=True,blank=True,default=None)
    date_data = models.TextField(null=True,blank=True,default=None)
    x_referred = models.TextField(null=True,blank=True,default=None)
    x_recnum = models.TextField(null=True,blank=True,default=None)
    date_admis = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    stock_num = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_ref

class RawLocation(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    ward = models.TextField(null=True,blank=True,default=None)
    institut = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    ward_type = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ward



class RawMicrobiology(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    organism = models.TextField(null=True,blank=True,default=None)
    org_type = models.TextField(null=True,blank=True,default=None)
    beta_lact = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    induc_cli = models.TextField(null=True,blank=True,default=None)
    x_meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    x_mrse = models.TextField(null=True,blank=True,default=None)
    x_carb = models.TextField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    urine_count = models.TextField(null=True,blank=True,default=None)
    serotype = models.TextField(null=True,blank=True,default=None)
    carbapenem = models.TextField(null=True,blank=True,default=None)
    mbl = models.TextField(null=True,blank=True,default=None)
    growth = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organism
    

class RawSpecimen(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    spec_num = models.TextField(null=True,blank=True,default=None)
    spec_date = models.TextField(null=True,blank=True,default=None)
    spec_type = models.TextField(null=True,blank=True,default=None)
    spec_code = models.TextField(null=True,blank=True,default=None)
    local_spec = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.spec_type



class RawAntidisk(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30 = models.TextField(null=True,blank=True,default=None)
    amc_nd20 = models.TextField(null=True,blank=True,default=None)
    amp_nd10 = models.TextField(null=True,blank=True,default=None)
    sam_nd10 = models.TextField(null=True,blank=True,default=None)
    azm_nd15 = models.TextField(null=True,blank=True,default=None)
    atm_nd30 = models.TextField(null=True,blank=True,default=None)
    cec_nd30 = models.TextField(null=True,blank=True,default=None)
    man_nd30 = models.TextField(null=True,blank=True,default=None)
    czo_nd30 = models.TextField(null=True,blank=True,default=None)
    fep_nd30 = models.TextField(null=True,blank=True,default=None)
    cfm_nd5 = models.TextField(null=True,blank=True,default=None)
    cfp_nd75 = models.TextField(null=True,blank=True,default=None)
    ctx_nd30 = models.TextField(null=True,blank=True,default=None)
    fox_nd30 = models.TextField(null=True,blank=True,default=None)
    caz_nd30 = models.TextField(null=True,blank=True,default=None)
    cro_nd30 = models.TextField(null=True,blank=True,default=None)
    cxm_nd30 = models.TextField(null=True,blank=True,default=None)
    cxa_nd30 = models.TextField(null=True,blank=True,default=None)
    cep_nd30 = models.TextField(null=True,blank=True,default=None)
    chl_nd30 = models.TextField(null=True,blank=True,default=None)
    cip_nd5 = models.TextField(null=True,blank=True,default=None)
    clr_nd15 = models.TextField(null=True,blank=True,default=None)
    cli_nd2 = models.TextField(null=True,blank=True,default=None)
    col_nd10 = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2 = models.TextField(null=True,blank=True,default=None)
    dap_nd30 = models.TextField(null=True,blank=True,default=None)
    dor_nd10 = models.TextField(null=True,blank=True,default=None)
    etp_nd10 = models.TextField(null=True,blank=True,default=None)
    ery_nd15 = models.TextField(null=True,blank=True,default=None)
    gen_nd10 = models.TextField(null=True,blank=True,default=None)
    geh_nd120 = models.TextField(null=True,blank=True,default=None)
    ipm_nd10 = models.TextField(null=True,blank=True,default=None)
    kan_nd30 = models.TextField(null=True,blank=True,default=None)
    lvx_nd5 = models.TextField(null=True,blank=True,default=None)
    lnz_nd30 = models.TextField(null=True,blank=True,default=None)
    mem_nd10 = models.TextField(null=True,blank=True,default=None)
    mno_nd30 = models.TextField(null=True,blank=True,default=None)
    mfx_nd5 = models.TextField(null=True,blank=True,default=None)
    nal_nd30 = models.TextField(null=True,blank=True,default=None)
    net_nd30 = models.TextField(null=True,blank=True,default=None)
    nit_nd300 = models.TextField(null=True,blank=True,default=None)
    nor_nd10 = models.TextField(null=True,blank=True,default=None)
    nov_nd5 = models.TextField(null=True,blank=True,default=None)
    ofx_nd5 = models.TextField(null=True,blank=True,default=None)
    oxa_nd1 = models.TextField(null=True,blank=True,default=None)
    pen_nd10 = models.TextField(null=True,blank=True,default=None)
    pip_nd100 = models.TextField(null=True,blank=True,default=None)
    tzp_nd100 = models.TextField(null=True,blank=True,default=None)
    pol_nd300 = models.TextField(null=True,blank=True,default=None)
    qda_nd15 = models.TextField(null=True,blank=True,default=None)
    rif_nd5 = models.TextField(null=True,blank=True,default=None)
    spt_nd100 = models.TextField(null=True,blank=True,default=None)
    str_nd10 = models.TextField(null=True,blank=True,default=None)
    sth_nd300 = models.TextField(null=True,blank=True,default=None)
    tcy_nd30 = models.TextField(null=True,blank=True,default=None)
    tic_nd75 = models.TextField(null=True,blank=True,default=None)
    tcc_nd75 = models.TextField(null=True,blank=True,default=None)
    tgc_nd15 = models.TextField(null=True,blank=True,default=None)
    tob_nd10 = models.TextField(null=True,blank=True,default=None)
    van_nd30 = models.TextField(null=True,blank=True,default=None)
    fos_nd200 = models.TextField(null=True,blank=True,default=None)
    dox_nd30 = models.TextField(null=True,blank=True,default=None)
    sss_nd200 = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class RawAntimic(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm = models.TextField(null=True,blank=True,default=None)
    amc_nm = models.TextField(null=True,blank=True,default=None)
    amp_nm = models.TextField(null=True,blank=True,default=None)
    sam_nm = models.TextField(null=True,blank=True,default=None)
    azm_nm = models.TextField(null=True,blank=True,default=None)
    atm_nm = models.TextField(null=True,blank=True,default=None)
    cec_nm = models.TextField(null=True,blank=True,default=None)
    man_nm = models.TextField(null=True,blank=True,default=None)
    czo_nm = models.TextField(null=True,blank=True,default=None)
    fep_nm = models.TextField(null=True,blank=True,default=None)
    cfm_nm = models.TextField(null=True,blank=True,default=None)
    cfp_nm = models.TextField(null=True,blank=True,default=None)
    ctx_nm = models.TextField(null=True,blank=True,default=None)
    fox_nm = models.TextField(null=True,blank=True,default=None)
    caz_nm = models.TextField(null=True,blank=True,default=None)
    cro_nm = models.TextField(null=True,blank=True,default=None)
    cxm_nm = models.TextField(null=True,blank=True,default=None)
    cxa_nm = models.TextField(null=True,blank=True,default=None)
    cep_nm = models.TextField(null=True,blank=True,default=None)
    chl_nm = models.TextField(null=True,blank=True,default=None)
    cip_nm = models.TextField(null=True,blank=True,default=None)
    clr_nm = models.TextField(null=True,blank=True,default=None)
    cli_nm = models.TextField(null=True,blank=True,default=None)
    col_nm = models.TextField(null=True,blank=True,default=None)
    sxt_nm = models.TextField(null=True,blank=True,default=None)
    dap_nm = models.TextField(null=True,blank=True,default=None)
    dor_nm = models.TextField(null=True,blank=True,default=None)
    etp_nm = models.TextField(null=True,blank=True,default=None)
    ery_nm = models.TextField(null=True,blank=True,default=None)
    gen_nm = models.TextField(null=True,blank=True,default=None)
    geh_nm = models.TextField(null=True,blank=True,default=None)
    ipm_nm = models.TextField(null=True,blank=True,default=None)
    kan_nm = models.TextField(null=True,blank=True,default=None)
    lvx_nm = models.TextField(null=True,blank=True,default=None)
    lnz_nm = models.TextField(null=True,blank=True,default=None)
    mem_nm = models.TextField(null=True,blank=True,default=None)
    mno_nm = models.TextField(null=True,blank=True,default=None)
    mfx_nm = models.TextField(null=True,blank=True,default=None)
    nal_nm = models.TextField(null=True,blank=True,default=None)
    net_nm = models.TextField(null=True,blank=True,default=None)
    nit_nm = models.TextField(null=True,blank=True,default=None)
    nor_nm = models.TextField(null=True,blank=True,default=None)
    nov_nm = models.TextField(null=True,blank=True,default=None)
    ofx_nm = models.TextField(null=True,blank=True,default=None)
    oxa_nm = models.TextField(null=True,blank=True,default=None)
    pen_nm = models.TextField(null=True,blank=True,default=None)
    pip_nm = models.TextField(null=True,blank=True,default=None)
    tzp_nm = models.TextField(null=True,blank=True,default=None)
    pol_nm = models.TextField(null=True,blank=True,default=None)
    qda_nm = models.TextField(null=True,blank=True,default=None)
    rif_nm = models.TextField(null=True,blank=True,default=None)
    spt_nm = models.TextField(null=True,blank=True,default=None)
    str_nm = models.TextField(null=True,blank=True,default=None)
    sth_nm = models.TextField(null=True,blank=True,default=None)
    tcy_nm = models.TextField(null=True,blank=True,default=None)
    tic_nm = models.TextField(null=True,blank=True,default=None)
    tcc_nm = models.TextField(null=True,blank=True,default=None)
    tgc_nm = models.TextField(null=True,blank=True,default=None)
    tob_nm = models.TextField(null=True,blank=True,default=None)
    van_nm = models.TextField(null=True,blank=True,default=None)
    fos_nm = models.TextField(null=True,blank=True,default=None)
    dox_nm = models.TextField(null=True,blank=True,default=None)
    sss_nm = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref


class RawAntietest(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_ne = models.TextField(null=True,blank=True,default=None)
    amc_ne = models.TextField(null=True,blank=True,default=None)
    amp_ne = models.TextField(null=True,blank=True,default=None)
    sam_ne = models.TextField(null=True,blank=True,default=None)
    azm_ne = models.TextField(null=True,blank=True,default=None)
    atm_ne = models.TextField(null=True,blank=True,default=None)
    cec_ne = models.TextField(null=True,blank=True,default=None)
    man_ne = models.TextField(null=True,blank=True,default=None)
    czo_ne = models.TextField(null=True,blank=True,default=None)
    fep_ne = models.TextField(null=True,blank=True,default=None)
    cfm_ne = models.TextField(null=True,blank=True,default=None)
    cfp_ne = models.TextField(null=True,blank=True,default=None)
    ctx_ne = models.TextField(null=True,blank=True,default=None)
    fox_ne = models.TextField(null=True,blank=True,default=None)
    caz_ne = models.TextField(null=True,blank=True,default=None)
    cro_ne = models.TextField(null=True,blank=True,default=None)
    cxm_ne = models.TextField(null=True,blank=True,default=None)
    cxa_ne = models.TextField(null=True,blank=True,default=None)
    cep_ne = models.TextField(null=True,blank=True,default=None)
    chl_ne = models.TextField(null=True,blank=True,default=None)
    cip_ne = models.TextField(null=True,blank=True,default=None)
    clr_ne = models.TextField(null=True,blank=True,default=None)
    cli_ne = models.TextField(null=True,blank=True,default=None)
    col_ne = models.TextField(null=True,blank=True,default=None)
    sxt_ne = models.TextField(null=True,blank=True,default=None)
    dap_ne = models.TextField(null=True,blank=True,default=None)
    dor_ne = models.TextField(null=True,blank=True,default=None)
    etp_ne = models.TextField(null=True,blank=True,default=None)
    ery_ne = models.TextField(null=True,blank=True,default=None)
    gen_ne = models.TextField(null=True,blank=True,default=None)
    geh_ne = models.TextField(null=True,blank=True,default=None)
    ipm_ne = models.TextField(null=True,blank=True,default=None)
    kan_ne = models.TextField(null=True,blank=True,default=None)
    lvx_ne = models.TextField(null=True,blank=True,default=None)
    lnz_ne = models.TextField(null=True,blank=True,default=None)
    mem_ne = models.TextField(null=True,blank=True,default=None)
    mno_ne = models.TextField(null=True,blank=True,default=None)
    mfx_ne = models.TextField(null=True,blank=True,default=None)
    nal_ne = models.TextField(null=True,blank=True,default=None)
    net_ne = models.TextField(null=True,blank=True,default=None)
    nit_ne = models.TextField(null=True,blank=True,default=None)
    nor_ne = models.TextField(null=True,blank=True,default=None)
    nov_ne = models.TextField(null=True,blank=True,default=None)
    ofx_ne = models.TextField(null=True,blank=True,default=None)
    oxa_ne = models.TextField(null=True,blank=True,default=None)
    pen_ne = models.TextField(null=True,blank=True,default=None)
    pip_ne = models.TextField(null=True,blank=True,default=None)
    tzp_ne = models.TextField(null=True,blank=True,default=None)
    pol_ne = models.TextField(null=True,blank=True,default=None)
    qda_ne = models.TextField(null=True,blank=True,default=None)
    rif_ne = models.TextField(null=True,blank=True,default=None)
    spt_ne = models.TextField(null=True,blank=True,default=None)
    str_ne = models.TextField(null=True,blank=True,default=None)
    sth_ne = models.TextField(null=True,blank=True,default=None)
    tcy_ne = models.TextField(null=True,blank=True,default=None)
    tic_ne = models.TextField(null=True,blank=True,default=None)
    tcc_ne = models.TextField(null=True,blank=True,default=None)
    tgc_ne = models.TextField(null=True,blank=True,default=None)
    tob_ne = models.TextField(null=True,blank=True,default=None)
    van_ne = models.TextField(null=True,blank=True,default=None)
    fos_ne = models.TextField(null=True,blank=True,default=None)
    dox_ne = models.TextField(null=True,blank=True,default=None)
    sss_ne = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    
    
    

#REFERRED DATA DITO ANG START


class ReferredFileName(models.Model):
    file_name = models.TextField(null=True,blank=True,default=None,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_name
    

class ReferredOrigin(models.Model):
    file_ref = models.ForeignKey(ReferredFileName, on_delete=models.CASCADE)
    country_a = models.TextField(null=True,blank=True,default=None)
    region = models.TextField(null=True,blank=True,default=None)
    island = models.TextField(null=True,blank=True,default=None)
    laboratory = models.TextField(null=True,blank=True,default=None)
    patient_id = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    mid_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_birth = models.TextField(null=True,blank=True,default=None)
    age_grp = models.TextField(null=True,blank=True,default=None)
    pat_type = models.TextField(null=True,blank=True,default=None)
    date_data = models.TextField(null=True,blank=True,default=None)
    x_referred = models.TextField(null=True,blank=True,default=None)
    x_recnum = models.TextField(null=True,blank=True,default=None)
    date_admis = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    diagnosis_text = models.TextField(null=True,blank=True,default=None)
    stock_num = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_ref

class ReferredLocation(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    ward = models.TextField(null=True,blank=True,default=None)
    institut = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    ward_type = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ward



class ReferredMicrobiology(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    organism = models.TextField(null=True,blank=True,default=None)
    org_type = models.TextField(null=True,blank=True,default=None)
    beta_lact = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    induc_cli = models.TextField(null=True,blank=True,default=None)
    x_meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    x_mrse = models.TextField(null=True,blank=True,default=None)
    # x_carb = models.TextField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    urine_count = models.TextField(null=True,blank=True,default=None)
    serotype = models.TextField(null=True,blank=True,default=None)
    mix_org1 = models.TextField(null=True,blank=True,default=None)
    mix_org2 = models.TextField(null=True,blank=True,default=None)
    antigenic = models.TextField(null=True,blank=True,default=None)
    carbapenem = models.TextField(null=True,blank=True,default=None)
    mbl = models.TextField(null=True,blank=True,default=None)
    growth = models.TextField(null=True,blank=True,default=None)
    arsrl_pre = models.TextField(null=True,blank=True,default=None)
    arsrl_final = models.TextField(null=True,blank=True,default=None)
    arsrl_post = models.TextField(null=True,blank=True,default=None)
    x_esbl_ct = models.TextField(null=True,blank=True,default=None)
    x_esbl_tz = models.TextField(null=True,blank=True,default=None)
    x_ip_ipi = models.TextField(null=True,blank=True,default=None)
    x_cn_cni = models.TextField(null=True,blank=True,default=None)
    edta = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organism
    

class ReferredSpecimen(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    spec_num = models.TextField(null=True,blank=True,default=None)
    spec_date = models.TextField(null=True,blank=True,default=None)
    spec_type = models.TextField(null=True,blank=True,default=None)
    spec_code = models.TextField(null=True,blank=True,default=None)
    local_spec = models.TextField(null=True,blank=True,default=None)
    date_refer = models.TextField(null=True,blank=True,default=None)
    reason = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.spec_type



class ReferredAntidisk(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30 = models.TextField(null=True,blank=True,default=None)
    amc_nd20 = models.TextField(null=True,blank=True,default=None)
    amp_nd10 = models.TextField(null=True,blank=True,default=None)
    sam_nd10 = models.TextField(null=True,blank=True,default=None)
    azm_nd15 = models.TextField(null=True,blank=True,default=None)
    atm_nd30 = models.TextField(null=True,blank=True,default=None)
    cec_nd30 = models.TextField(null=True,blank=True,default=None)
    man_nd30 = models.TextField(null=True,blank=True,default=None)
    czo_nd30 = models.TextField(null=True,blank=True,default=None)
    fep_nd30 = models.TextField(null=True,blank=True,default=None)
    cfm_nd5 = models.TextField(null=True,blank=True,default=None)
    cfp_nd75 = models.TextField(null=True,blank=True,default=None)
    ctx_nd30 = models.TextField(null=True,blank=True,default=None)
    fox_nd30 = models.TextField(null=True,blank=True,default=None)
    caz_nd30 = models.TextField(null=True,blank=True,default=None)
    cro_nd30 = models.TextField(null=True,blank=True,default=None)
    cxm_nd30 = models.TextField(null=True,blank=True,default=None)
    cxa_nd30 = models.TextField(null=True,blank=True,default=None)
    cep_nd30 = models.TextField(null=True,blank=True,default=None)
    chl_nd30 = models.TextField(null=True,blank=True,default=None)
    cip_nd5 = models.TextField(null=True,blank=True,default=None)
    clr_nd15 = models.TextField(null=True,blank=True,default=None)
    cli_nd2 = models.TextField(null=True,blank=True,default=None)
    col_nd10 = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2 = models.TextField(null=True,blank=True,default=None)
    dap_nd30 = models.TextField(null=True,blank=True,default=None)
    dor_nd10 = models.TextField(null=True,blank=True,default=None)
    etp_nd10 = models.TextField(null=True,blank=True,default=None)
    ery_nd15 = models.TextField(null=True,blank=True,default=None)
    gen_nd10 = models.TextField(null=True,blank=True,default=None)
    geh_nd120 = models.TextField(null=True,blank=True,default=None)
    ipm_nd10 = models.TextField(null=True,blank=True,default=None)
    kan_nd30 = models.TextField(null=True,blank=True,default=None)
    lvx_nd5 = models.TextField(null=True,blank=True,default=None)
    lnz_nd30 = models.TextField(null=True,blank=True,default=None)
    mem_nd10 = models.TextField(null=True,blank=True,default=None)
    mno_nd30 = models.TextField(null=True,blank=True,default=None)
    mfx_nd5 = models.TextField(null=True,blank=True,default=None)
    nal_nd30 = models.TextField(null=True,blank=True,default=None)
    net_nd30 = models.TextField(null=True,blank=True,default=None)
    nit_nd300 = models.TextField(null=True,blank=True,default=None)
    nor_nd10 = models.TextField(null=True,blank=True,default=None)
    nov_nd5 = models.TextField(null=True,blank=True,default=None)
    ofx_nd5 = models.TextField(null=True,blank=True,default=None)
    oxa_nd1 = models.TextField(null=True,blank=True,default=None)
    pen_nd10 = models.TextField(null=True,blank=True,default=None)
    pip_nd100 = models.TextField(null=True,blank=True,default=None)
    tzp_nd100 = models.TextField(null=True,blank=True,default=None)
    pol_nd300 = models.TextField(null=True,blank=True,default=None)
    qda_nd15 = models.TextField(null=True,blank=True,default=None)
    rif_nd5 = models.TextField(null=True,blank=True,default=None)
    spt_nd100 = models.TextField(null=True,blank=True,default=None)
    str_nd10 = models.TextField(null=True,blank=True,default=None)
    sth_nd300 = models.TextField(null=True,blank=True,default=None)
    tcy_nd30 = models.TextField(null=True,blank=True,default=None)
    tic_nd75 = models.TextField(null=True,blank=True,default=None)
    tcc_nd75 = models.TextField(null=True,blank=True,default=None)
    tgc_nd15 = models.TextField(null=True,blank=True,default=None)
    tob_nd10 = models.TextField(null=True,blank=True,default=None)
    van_nd30 = models.TextField(null=True,blank=True,default=None)
    fos_nd200 = models.TextField(null=True,blank=True,default=None)
    dox_nd30 = models.TextField(null=True,blank=True,default=None)
    sss_nd200 = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class ReferredAntimic(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm = models.TextField(null=True,blank=True,default=None)
    amc_nm = models.TextField(null=True,blank=True,default=None)
    amp_nm = models.TextField(null=True,blank=True,default=None)
    sam_nm = models.TextField(null=True,blank=True,default=None)
    azm_nm = models.TextField(null=True,blank=True,default=None)
    atm_nm = models.TextField(null=True,blank=True,default=None)
    cec_nm = models.TextField(null=True,blank=True,default=None)
    man_nm = models.TextField(null=True,blank=True,default=None)
    czo_nm = models.TextField(null=True,blank=True,default=None)
    fep_nm = models.TextField(null=True,blank=True,default=None)
    cfm_nm = models.TextField(null=True,blank=True,default=None)
    cfp_nm = models.TextField(null=True,blank=True,default=None)
    ctx_nm = models.TextField(null=True,blank=True,default=None)
    fox_nm = models.TextField(null=True,blank=True,default=None)
    caz_nm = models.TextField(null=True,blank=True,default=None)
    cro_nm = models.TextField(null=True,blank=True,default=None)
    cxm_nm = models.TextField(null=True,blank=True,default=None)
    cxa_nm = models.TextField(null=True,blank=True,default=None)
    cep_nm = models.TextField(null=True,blank=True,default=None)
    chl_nm = models.TextField(null=True,blank=True,default=None)
    cip_nm = models.TextField(null=True,blank=True,default=None)
    clr_nm = models.TextField(null=True,blank=True,default=None)
    cli_nm = models.TextField(null=True,blank=True,default=None)
    col_nm = models.TextField(null=True,blank=True,default=None)
    sxt_nm = models.TextField(null=True,blank=True,default=None)
    dap_nm = models.TextField(null=True,blank=True,default=None)
    dor_nm = models.TextField(null=True,blank=True,default=None)
    etp_nm = models.TextField(null=True,blank=True,default=None)
    ery_nm = models.TextField(null=True,blank=True,default=None)
    gen_nm = models.TextField(null=True,blank=True,default=None)
    geh_nm = models.TextField(null=True,blank=True,default=None)
    ipm_nm = models.TextField(null=True,blank=True,default=None)
    kan_nm = models.TextField(null=True,blank=True,default=None)
    lvx_nm = models.TextField(null=True,blank=True,default=None)
    lnz_nm = models.TextField(null=True,blank=True,default=None)
    mem_nm = models.TextField(null=True,blank=True,default=None)
    mno_nm = models.TextField(null=True,blank=True,default=None)
    mfx_nm = models.TextField(null=True,blank=True,default=None)
    nal_nm = models.TextField(null=True,blank=True,default=None)
    net_nm = models.TextField(null=True,blank=True,default=None)
    nit_nm = models.TextField(null=True,blank=True,default=None)
    nor_nm = models.TextField(null=True,blank=True,default=None)
    nov_nm = models.TextField(null=True,blank=True,default=None)
    ofx_nm = models.TextField(null=True,blank=True,default=None)
    oxa_nm = models.TextField(null=True,blank=True,default=None)
    pen_nm = models.TextField(null=True,blank=True,default=None)
    pip_nm = models.TextField(null=True,blank=True,default=None)
    tzp_nm = models.TextField(null=True,blank=True,default=None)
    pol_nm = models.TextField(null=True,blank=True,default=None)
    qda_nm = models.TextField(null=True,blank=True,default=None)
    rif_nm = models.TextField(null=True,blank=True,default=None)
    spt_nm = models.TextField(null=True,blank=True,default=None)
    str_nm = models.TextField(null=True,blank=True,default=None)
    sth_nm = models.TextField(null=True,blank=True,default=None)
    tcy_nm = models.TextField(null=True,blank=True,default=None)
    tic_nm = models.TextField(null=True,blank=True,default=None)
    tcc_nm = models.TextField(null=True,blank=True,default=None)
    tgc_nm = models.TextField(null=True,blank=True,default=None)
    tob_nm = models.TextField(null=True,blank=True,default=None)
    van_nm = models.TextField(null=True,blank=True,default=None)
    fos_nm = models.TextField(null=True,blank=True,default=None)
    dox_nm = models.TextField(null=True,blank=True,default=None)
    sss_nm = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref


class ReferredAntidiskris(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30_ris = models.TextField(null=True,blank=True,default=None)
    amc_nd20_ris = models.TextField(null=True,blank=True,default=None)
    amp_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sam_nd10_ris = models.TextField(null=True,blank=True,default=None)
    azm_nd15_ris = models.TextField(null=True,blank=True,default=None)
    atm_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cec_nd30_ris = models.TextField(null=True,blank=True,default=None)
    man_nd30_ris = models.TextField(null=True,blank=True,default=None)
    czo_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fep_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cfm_nd5_ris = models.TextField(null=True,blank=True,default=None)
    cfp_nd75_ris = models.TextField(null=True,blank=True,default=None)
    ctx_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fox_nd30_ris = models.TextField(null=True,blank=True,default=None)
    caz_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cro_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cxm_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cxa_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cep_nd30_ris = models.TextField(null=True,blank=True,default=None)
    chl_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cip_nd5_ris = models.TextField(null=True,blank=True,default=None)
    clr_nd15_ris = models.TextField(null=True,blank=True,default=None)
    cli_nd2_ris = models.TextField(null=True,blank=True,default=None)
    col_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2_ris = models.TextField(null=True,blank=True,default=None)
    dap_nd30_ris = models.TextField(null=True,blank=True,default=None)
    dor_nd10_ris = models.TextField(null=True,blank=True,default=None)
    etp_nd10_ris = models.TextField(null=True,blank=True,default=None)
    ery_nd15_ris = models.TextField(null=True,blank=True,default=None)
    gen_nd10_ris = models.TextField(null=True,blank=True,default=None)
    geh_nd120_ris = models.TextField(null=True,blank=True,default=None)
    ipm_nd10_ris = models.TextField(null=True,blank=True,default=None)
    kan_nd30_ris = models.TextField(null=True,blank=True,default=None)
    lvx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    lnz_nd30_ris = models.TextField(null=True,blank=True,default=None)
    mem_nd10_ris = models.TextField(null=True,blank=True,default=None)
    mno_nd30_ris = models.TextField(null=True,blank=True,default=None)
    mfx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    nal_nd30_ris = models.TextField(null=True,blank=True,default=None)
    net_nd30_ris = models.TextField(null=True,blank=True,default=None)
    nit_nd300_ris = models.TextField(null=True,blank=True,default=None)
    nor_nd10_ris = models.TextField(null=True,blank=True,default=None)
    nov_nd5_ris = models.TextField(null=True,blank=True,default=None)
    ofx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    oxa_nd1_ris = models.TextField(null=True,blank=True,default=None)
    pen_nd10_ris = models.TextField(null=True,blank=True,default=None)
    pip_nd100_ris = models.TextField(null=True,blank=True,default=None)
    tzp_nd100_ris = models.TextField(null=True,blank=True,default=None)
    pol_nd300_ris = models.TextField(null=True,blank=True,default=None)
    qda_nd15_ris = models.TextField(null=True,blank=True,default=None)
    rif_nd5_ris = models.TextField(null=True,blank=True,default=None)
    spt_nd100_ris = models.TextField(null=True,blank=True,default=None)
    str_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sth_nd300_ris = models.TextField(null=True,blank=True,default=None)
    tcy_nd30_ris = models.TextField(null=True,blank=True,default=None)
    tic_nd75_ris = models.TextField(null=True,blank=True,default=None)
    tcc_nd75_ris = models.TextField(null=True,blank=True,default=None)
    tgc_nd15_ris = models.TextField(null=True,blank=True,default=None)
    tob_nd10_ris = models.TextField(null=True,blank=True,default=None)
    van_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fos_nd200_ris = models.TextField(null=True,blank=True,default=None)
    dox_nd30_ris = models.TextField(null=True,blank=True,default=None)
    sss_nd200_ris = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class ReferredAntimicris(models.Model):
    origin_ref = models.OneToOneField(ReferredOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm_ris = models.TextField(null=True,blank=True,default=None)
    amc_nm_ris = models.TextField(null=True,blank=True,default=None)
    amp_nm_ris = models.TextField(null=True,blank=True,default=None)
    sam_nm_ris = models.TextField(null=True,blank=True,default=None)
    azm_nm_ris = models.TextField(null=True,blank=True,default=None)
    atm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cec_nm_ris = models.TextField(null=True,blank=True,default=None)
    man_nm_ris = models.TextField(null=True,blank=True,default=None)
    czo_nm_ris = models.TextField(null=True,blank=True,default=None)
    fep_nm_ris = models.TextField(null=True,blank=True,default=None)
    cfm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cfp_nm_ris = models.TextField(null=True,blank=True,default=None)
    ctx_nm_ris = models.TextField(null=True,blank=True,default=None)
    fox_nm_ris = models.TextField(null=True,blank=True,default=None)
    caz_nm_ris = models.TextField(null=True,blank=True,default=None)
    cro_nm_ris = models.TextField(null=True,blank=True,default=None)
    cxm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cxa_nm_ris = models.TextField(null=True,blank=True,default=None)
    cep_nm_ris = models.TextField(null=True,blank=True,default=None)
    chl_nm_ris = models.TextField(null=True,blank=True,default=None)
    cip_nm_ris = models.TextField(null=True,blank=True,default=None)
    clr_nm_ris = models.TextField(null=True,blank=True,default=None)
    cli_nm_ris = models.TextField(null=True,blank=True,default=None)
    col_nm_ris = models.TextField(null=True,blank=True,default=None)
    sxt_nm_ris = models.TextField(null=True,blank=True,default=None)
    dap_nm_ris = models.TextField(null=True,blank=True,default=None)
    dor_nm_ris = models.TextField(null=True,blank=True,default=None)
    etp_nm_ris = models.TextField(null=True,blank=True,default=None)
    ery_nm_ris = models.TextField(null=True,blank=True,default=None)
    gen_nm_ris = models.TextField(null=True,blank=True,default=None)
    geh_nm_ris = models.TextField(null=True,blank=True,default=None)
    ipm_nm_ris = models.TextField(null=True,blank=True,default=None)
    kan_nm_ris = models.TextField(null=True,blank=True,default=None)
    lvx_nm_ris = models.TextField(null=True,blank=True,default=None)
    lnz_nm_ris = models.TextField(null=True,blank=True,default=None)
    mem_nm_ris = models.TextField(null=True,blank=True,default=None)
    mno_nm_ris = models.TextField(null=True,blank=True,default=None)
    mfx_nm_ris = models.TextField(null=True,blank=True,default=None)
    nal_nm_ris = models.TextField(null=True,blank=True,default=None)
    net_nm_ris = models.TextField(null=True,blank=True,default=None)
    nit_nm_ris = models.TextField(null=True,blank=True,default=None)
    nor_nm_ris = models.TextField(null=True,blank=True,default=None)
    nov_nm_ris = models.TextField(null=True,blank=True,default=None)
    ofx_nm_ris = models.TextField(null=True,blank=True,default=None)
    oxa_nm_ris = models.TextField(null=True,blank=True,default=None)
    pen_nm_ris = models.TextField(null=True,blank=True,default=None)
    pip_nm_ris = models.TextField(null=True,blank=True,default=None)
    tzp_nm_ris = models.TextField(null=True,blank=True,default=None)
    pol_nm_ris = models.TextField(null=True,blank=True,default=None)
    qda_nm_ris = models.TextField(null=True,blank=True,default=None)
    rif_nm_ris = models.TextField(null=True,blank=True,default=None)
    spt_nm_ris = models.TextField(null=True,blank=True,default=None)
    str_nm_ris = models.TextField(null=True,blank=True,default=None)
    sth_nm_ris = models.TextField(null=True,blank=True,default=None)
    tcy_nm_ris = models.TextField(null=True,blank=True,default=None)
    tic_nm_ris = models.TextField(null=True,blank=True,default=None)
    tcc_nm_ris = models.TextField(null=True,blank=True,default=None)
    tgc_nm_ris = models.TextField(null=True,blank=True,default=None)
    tob_nm_ris = models.TextField(null=True,blank=True,default=None)
    van_nm_ris = models.TextField(null=True,blank=True,default=None)
    fos_nm_ris = models.TextField(null=True,blank=True,default=None)
    dox_nm_ris = models.TextField(null=True,blank=True,default=None)
    sss_nm_ris = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    
    

# FINAL DATA IMPORT START

class FinalFileName(models.Model):
    file_name = models.TextField(null=True,blank=True,default=None,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_name
    

class FinalOrigin(models.Model):
    file_ref = models.ForeignKey(FinalFileName, on_delete=models.CASCADE)
    country_a = models.TextField(null=True,blank=True,default=None)
    region = models.TextField(null=True,blank=True,default=None)
    island = models.TextField(null=True,blank=True,default=None)
    laboratory = models.TextField(null=True,blank=True,default=None)
    patient_id = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    mid_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_birth = models.TextField(null=True,blank=True,default=None)
    age_grp = models.TextField(null=True,blank=True,default=None)
    pat_type = models.TextField(null=True,blank=True,default=None)
    date_data = models.TextField(null=True,blank=True,default=None)
    x_referred = models.TextField(null=True,blank=True,default=None)
    x_recnum = models.TextField(null=True,blank=True,default=None)
    date_admis = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    stock_num = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_ref

class FinalLocation(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    ward = models.TextField(null=True,blank=True,default=None)
    institut = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    ward_type = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ward



class FinalMicrobiology(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    organism = models.TextField(null=True,blank=True,default=None)
    org_type = models.TextField(null=True,blank=True,default=None)
    beta_lact = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    induc_cli = models.TextField(null=True,blank=True,default=None)
    x_meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    x_mrse = models.TextField(null=True,blank=True,default=None)
    x_carb = models.TextField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    urine_count = models.TextField(null=True,blank=True,default=None)
    serotype = models.TextField(null=True,blank=True,default=None)
    carbapenem = models.TextField(null=True,blank=True,default=None)
    mbl = models.TextField(null=True,blank=True,default=None)
    growth = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organism
    

class FinalSpecimen(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    spec_num = models.TextField(null=True,blank=True,default=None)
    spec_date = models.TextField(null=True,blank=True,default=None)
    spec_type = models.TextField(null=True,blank=True,default=None)
    spec_code = models.TextField(null=True,blank=True,default=None)
    local_spec = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.spec_type



class FinalAntidisk(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30 = models.TextField(null=True,blank=True,default=None)
    amc_nd20 = models.TextField(null=True,blank=True,default=None)
    amp_nd10 = models.TextField(null=True,blank=True,default=None)
    sam_nd10 = models.TextField(null=True,blank=True,default=None)
    azm_nd15 = models.TextField(null=True,blank=True,default=None)
    atm_nd30 = models.TextField(null=True,blank=True,default=None)
    cec_nd30 = models.TextField(null=True,blank=True,default=None)
    man_nd30 = models.TextField(null=True,blank=True,default=None)
    czo_nd30 = models.TextField(null=True,blank=True,default=None)
    fep_nd30 = models.TextField(null=True,blank=True,default=None)
    cfm_nd5 = models.TextField(null=True,blank=True,default=None)
    cfp_nd75 = models.TextField(null=True,blank=True,default=None)
    ctx_nd30 = models.TextField(null=True,blank=True,default=None)
    fox_nd30 = models.TextField(null=True,blank=True,default=None)
    caz_nd30 = models.TextField(null=True,blank=True,default=None)
    cro_nd30 = models.TextField(null=True,blank=True,default=None)
    cxm_nd30 = models.TextField(null=True,blank=True,default=None)
    cxa_nd30 = models.TextField(null=True,blank=True,default=None)
    cep_nd30 = models.TextField(null=True,blank=True,default=None)
    chl_nd30 = models.TextField(null=True,blank=True,default=None)
    cip_nd5 = models.TextField(null=True,blank=True,default=None)
    clr_nd15 = models.TextField(null=True,blank=True,default=None)
    cli_nd2 = models.TextField(null=True,blank=True,default=None)
    col_nd10 = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2 = models.TextField(null=True,blank=True,default=None)
    dap_nd30 = models.TextField(null=True,blank=True,default=None)
    dor_nd10 = models.TextField(null=True,blank=True,default=None)
    etp_nd10 = models.TextField(null=True,blank=True,default=None)
    ery_nd15 = models.TextField(null=True,blank=True,default=None)
    gen_nd10 = models.TextField(null=True,blank=True,default=None)
    geh_nd120 = models.TextField(null=True,blank=True,default=None)
    ipm_nd10 = models.TextField(null=True,blank=True,default=None)
    kan_nd30 = models.TextField(null=True,blank=True,default=None)
    lvx_nd5 = models.TextField(null=True,blank=True,default=None)
    lnz_nd30 = models.TextField(null=True,blank=True,default=None)
    mem_nd10 = models.TextField(null=True,blank=True,default=None)
    mno_nd30 = models.TextField(null=True,blank=True,default=None)
    mfx_nd5 = models.TextField(null=True,blank=True,default=None)
    nal_nd30 = models.TextField(null=True,blank=True,default=None)
    net_nd30 = models.TextField(null=True,blank=True,default=None)
    nit_nd300 = models.TextField(null=True,blank=True,default=None)
    nor_nd10 = models.TextField(null=True,blank=True,default=None)
    nov_nd5 = models.TextField(null=True,blank=True,default=None)
    ofx_nd5 = models.TextField(null=True,blank=True,default=None)
    oxa_nd1 = models.TextField(null=True,blank=True,default=None)
    pen_nd10 = models.TextField(null=True,blank=True,default=None)
    pip_nd100 = models.TextField(null=True,blank=True,default=None)
    tzp_nd100 = models.TextField(null=True,blank=True,default=None)
    pol_nd300 = models.TextField(null=True,blank=True,default=None)
    qda_nd15 = models.TextField(null=True,blank=True,default=None)
    rif_nd5 = models.TextField(null=True,blank=True,default=None)
    spt_nd100 = models.TextField(null=True,blank=True,default=None)
    str_nd10 = models.TextField(null=True,blank=True,default=None)
    sth_nd300 = models.TextField(null=True,blank=True,default=None)
    tcy_nd30 = models.TextField(null=True,blank=True,default=None)
    tic_nd75 = models.TextField(null=True,blank=True,default=None)
    tcc_nd75 = models.TextField(null=True,blank=True,default=None)
    tgc_nd15 = models.TextField(null=True,blank=True,default=None)
    tob_nd10 = models.TextField(null=True,blank=True,default=None)
    van_nd30 = models.TextField(null=True,blank=True,default=None)
    fos_nd200 = models.TextField(null=True,blank=True,default=None)
    dox_nd30 = models.TextField(null=True,blank=True,default=None)
    sss_nd200 = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class FinalAntimic(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm = models.TextField(null=True,blank=True,default=None)
    amc_nm = models.TextField(null=True,blank=True,default=None)
    amp_nm = models.TextField(null=True,blank=True,default=None)
    sam_nm = models.TextField(null=True,blank=True,default=None)
    azm_nm = models.TextField(null=True,blank=True,default=None)
    atm_nm = models.TextField(null=True,blank=True,default=None)
    cec_nm = models.TextField(null=True,blank=True,default=None)
    man_nm = models.TextField(null=True,blank=True,default=None)
    czo_nm = models.TextField(null=True,blank=True,default=None)
    fep_nm = models.TextField(null=True,blank=True,default=None)
    cfm_nm = models.TextField(null=True,blank=True,default=None)
    cfp_nm = models.TextField(null=True,blank=True,default=None)
    ctx_nm = models.TextField(null=True,blank=True,default=None)
    fox_nm = models.TextField(null=True,blank=True,default=None)
    caz_nm = models.TextField(null=True,blank=True,default=None)
    cro_nm = models.TextField(null=True,blank=True,default=None)
    cxm_nm = models.TextField(null=True,blank=True,default=None)
    cxa_nm = models.TextField(null=True,blank=True,default=None)
    cep_nm = models.TextField(null=True,blank=True,default=None)
    chl_nm = models.TextField(null=True,blank=True,default=None)
    cip_nm = models.TextField(null=True,blank=True,default=None)
    clr_nm = models.TextField(null=True,blank=True,default=None)
    cli_nm = models.TextField(null=True,blank=True,default=None)
    col_nm = models.TextField(null=True,blank=True,default=None)
    sxt_nm = models.TextField(null=True,blank=True,default=None)
    dap_nm = models.TextField(null=True,blank=True,default=None)
    dor_nm = models.TextField(null=True,blank=True,default=None)
    etp_nm = models.TextField(null=True,blank=True,default=None)
    ery_nm = models.TextField(null=True,blank=True,default=None)
    gen_nm = models.TextField(null=True,blank=True,default=None)
    geh_nm = models.TextField(null=True,blank=True,default=None)
    ipm_nm = models.TextField(null=True,blank=True,default=None)
    kan_nm = models.TextField(null=True,blank=True,default=None)
    lvx_nm = models.TextField(null=True,blank=True,default=None)
    lnz_nm = models.TextField(null=True,blank=True,default=None)
    mem_nm = models.TextField(null=True,blank=True,default=None)
    mno_nm = models.TextField(null=True,blank=True,default=None)
    mfx_nm = models.TextField(null=True,blank=True,default=None)
    nal_nm = models.TextField(null=True,blank=True,default=None)
    net_nm = models.TextField(null=True,blank=True,default=None)
    nit_nm = models.TextField(null=True,blank=True,default=None)
    nor_nm = models.TextField(null=True,blank=True,default=None)
    nov_nm = models.TextField(null=True,blank=True,default=None)
    ofx_nm = models.TextField(null=True,blank=True,default=None)
    oxa_nm = models.TextField(null=True,blank=True,default=None)
    pen_nm = models.TextField(null=True,blank=True,default=None)
    pip_nm = models.TextField(null=True,blank=True,default=None)
    tzp_nm = models.TextField(null=True,blank=True,default=None)
    pol_nm = models.TextField(null=True,blank=True,default=None)
    qda_nm = models.TextField(null=True,blank=True,default=None)
    rif_nm = models.TextField(null=True,blank=True,default=None)
    spt_nm = models.TextField(null=True,blank=True,default=None)
    str_nm = models.TextField(null=True,blank=True,default=None)
    sth_nm = models.TextField(null=True,blank=True,default=None)
    tcy_nm = models.TextField(null=True,blank=True,default=None)
    tic_nm = models.TextField(null=True,blank=True,default=None)
    tcc_nm = models.TextField(null=True,blank=True,default=None)
    tgc_nm = models.TextField(null=True,blank=True,default=None)
    tob_nm = models.TextField(null=True,blank=True,default=None)
    van_nm = models.TextField(null=True,blank=True,default=None)
    fos_nm = models.TextField(null=True,blank=True,default=None)
    dox_nm = models.TextField(null=True,blank=True,default=None)
    sss_nm = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref

    
    
class FinalAntietest(models.Model):
    origin_ref = models.OneToOneField(FinalOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_ne = models.TextField(null=True,blank=True,default=None)
    amc_ne = models.TextField(null=True,blank=True,default=None)
    amp_ne = models.TextField(null=True,blank=True,default=None)
    sam_ne = models.TextField(null=True,blank=True,default=None)
    azm_ne = models.TextField(null=True,blank=True,default=None)
    atm_ne = models.TextField(null=True,blank=True,default=None)
    cec_ne = models.TextField(null=True,blank=True,default=None)
    man_ne = models.TextField(null=True,blank=True,default=None)
    czo_ne = models.TextField(null=True,blank=True,default=None)
    fep_ne = models.TextField(null=True,blank=True,default=None)
    cfm_ne = models.TextField(null=True,blank=True,default=None)
    cfp_ne = models.TextField(null=True,blank=True,default=None)
    ctx_ne = models.TextField(null=True,blank=True,default=None)
    fox_ne = models.TextField(null=True,blank=True,default=None)
    caz_ne = models.TextField(null=True,blank=True,default=None)
    cro_ne = models.TextField(null=True,blank=True,default=None)
    cxm_ne = models.TextField(null=True,blank=True,default=None)
    cxa_ne = models.TextField(null=True,blank=True,default=None)
    cep_ne = models.TextField(null=True,blank=True,default=None)
    chl_ne = models.TextField(null=True,blank=True,default=None)
    cip_ne = models.TextField(null=True,blank=True,default=None)
    clr_ne = models.TextField(null=True,blank=True,default=None)
    cli_ne = models.TextField(null=True,blank=True,default=None)
    col_ne = models.TextField(null=True,blank=True,default=None)
    sxt_ne = models.TextField(null=True,blank=True,default=None)
    dap_ne = models.TextField(null=True,blank=True,default=None)
    dor_ne = models.TextField(null=True,blank=True,default=None)
    etp_ne = models.TextField(null=True,blank=True,default=None)
    ery_ne = models.TextField(null=True,blank=True,default=None)
    gen_ne = models.TextField(null=True,blank=True,default=None)
    geh_ne = models.TextField(null=True,blank=True,default=None)
    ipm_ne = models.TextField(null=True,blank=True,default=None)
    kan_ne = models.TextField(null=True,blank=True,default=None)
    lvx_ne = models.TextField(null=True,blank=True,default=None)
    lnz_ne = models.TextField(null=True,blank=True,default=None)
    mem_ne = models.TextField(null=True,blank=True,default=None)
    mno_ne = models.TextField(null=True,blank=True,default=None)
    mfx_ne = models.TextField(null=True,blank=True,default=None)
    nal_ne = models.TextField(null=True,blank=True,default=None)
    net_ne = models.TextField(null=True,blank=True,default=None)
    nit_ne = models.TextField(null=True,blank=True,default=None)
    nor_ne = models.TextField(null=True,blank=True,default=None)
    nov_ne = models.TextField(null=True,blank=True,default=None)
    ofx_ne = models.TextField(null=True,blank=True,default=None)
    oxa_ne = models.TextField(null=True,blank=True,default=None)
    pen_ne = models.TextField(null=True,blank=True,default=None)
    pip_ne = models.TextField(null=True,blank=True,default=None)
    tzp_ne = models.TextField(null=True,blank=True,default=None)
    pol_ne = models.TextField(null=True,blank=True,default=None)
    qda_ne = models.TextField(null=True,blank=True,default=None)
    rif_ne = models.TextField(null=True,blank=True,default=None)
    spt_ne = models.TextField(null=True,blank=True,default=None)
    str_ne = models.TextField(null=True,blank=True,default=None)
    sth_ne = models.TextField(null=True,blank=True,default=None)
    tcy_ne = models.TextField(null=True,blank=True,default=None)
    tic_ne = models.TextField(null=True,blank=True,default=None)
    tcc_ne = models.TextField(null=True,blank=True,default=None)
    tgc_ne = models.TextField(null=True,blank=True,default=None)
    tob_ne = models.TextField(null=True,blank=True,default=None)
    van_ne = models.TextField(null=True,blank=True,default=None)
    fos_ne = models.TextField(null=True,blank=True,default=None)
    dox_ne = models.TextField(null=True,blank=True,default=None)
    sss_ne = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref


## GHRU tables

class EpiMetaData(models.Model):
    sample_id = models.TextField(null=True,blank=True,default=None,unique=True)
    alternative_sample_id = models.TextField(null=True,blank=True,default=None)
    ghru_uuid = models.TextField(null=True,blank=True,default=None)
    species = models.TextField(null=True,blank=True,default=None)
    wgs_id = models.TextField(null=True,blank=True,default=None)
    wgs_qc = models.TextField(null=True,blank=True,default=None)
    country = models.TextField(null=True,blank=True,default=None)
    country_alpha_2_code = models.TextField(null=True,blank=True,default=None)
    region_province_department = models.TextField(null=True,blank=True,default=None)
    iso_3166_2_subdivision_code = models.TextField(null=True,blank=True,default=None)
    location = models.TextField(null=True,blank=True,default=None)
    sentinel_site_code = models.TextField(null=True,blank=True,default=None)
    latitude = models.TextField(null=True,blank=True,default=None)
    longitude = models.TextField(null=True,blank=True,default=None)
    collected_by = models.TextField(null=True,blank=True,default=None)
    collection_contact = models.TextField(null=True,blank=True,default=None)
    collection_date = models.TextField(null=True,blank=True,default=None)
    year = models.TextField(null=True,blank=True,default=None)
    month = models.TextField(null=True,blank=True,default=None)
    day = models.TextField(null=True,blank=True,default=None)
    outbreak_isolate = models.TextField(null=True,blank=True,default=None)
    clinical_significance = models.TextField(null=True,blank=True,default=None)
    host = models.TextField(null=True,blank=True,default=None)
    specimen_type = models.TextField(null=True,blank=True,default=None)
    invasive = models.TextField(null=True,blank=True,default=None)
    patient_type = models.TextField(null=True,blank=True,default=None)
    ward_inpatients_only = models.TextField(null=True,blank=True,default=None)
    room_inpatients_only = models.TextField(null=True,blank=True,default=None)
    address_outpatients_only = models.TextField(null=True,blank=True,default=None)
    address_latitude_outpatients_only = models.TextField(null=True,blank=True,default=None)
    address_longitude_outpatients_only = models.TextField(null=True,blank=True,default=None)
    origin = models.TextField(null=True,blank=True,default=None)
    hai_type = models.TextField(null=True,blank=True,default=None)
    patient_date_of_birth = models.TextField(null=True,blank=True,default=None)
    patient_age = models.TextField(null=True,blank=True,default=None)
    patient_gender = models.TextField(null=True,blank=True,default=None)
    clinical_diagnosis = models.TextField(null=True,blank=True,default=None)
    submitted_as = models.TextField(null=True,blank=True,default=None)
    instrument = models.TextField(null=True,blank=True,default=None)
    card_code = models.TextField(null=True,blank=True,default=None)
    ast_profile = models.TextField(null=True,blank=True,default=None)
    abx_amc = models.TextField(null=True,blank=True,default=None)
    abx_amk = models.TextField(null=True,blank=True,default=None)
    abx_amp = models.TextField(null=True,blank=True,default=None)
    abx_atm = models.TextField(null=True,blank=True,default=None)
    abx_azm = models.TextField(null=True,blank=True,default=None)
    abx_caz = models.TextField(null=True,blank=True,default=None)
    abx_cec = models.TextField(null=True,blank=True,default=None)
    abx_cep = models.TextField(null=True,blank=True,default=None)
    abx_cfm = models.TextField(null=True,blank=True,default=None)
    abx_chl = models.TextField(null=True,blank=True,default=None)
    abx_cip = models.TextField(null=True,blank=True,default=None)
    abx_cli = models.TextField(null=True,blank=True,default=None)
    abx_col = models.TextField(null=True,blank=True,default=None)
    abx_cro = models.TextField(null=True,blank=True,default=None)
    abx_csl = models.TextField(null=True,blank=True,default=None)
    abx_ctx = models.TextField(null=True,blank=True,default=None)
    abx_cxa = models.TextField(null=True,blank=True,default=None)
    abx_cxm = models.TextField(null=True,blank=True,default=None)
    abx_czo = models.TextField(null=True,blank=True,default=None)
    abx_dap = models.TextField(null=True,blank=True,default=None)
    abx_dor = models.TextField(null=True,blank=True,default=None)
    abx_enr = models.TextField(null=True,blank=True,default=None)
    abx_ery = models.TextField(null=True,blank=True,default=None)
    abx_etp = models.TextField(null=True,blank=True,default=None)
    abx_fep = models.TextField(null=True,blank=True,default=None)
    abx_fox = models.TextField(null=True,blank=True,default=None)
    abx_gen = models.TextField(null=True,blank=True,default=None)
    abx_ipm = models.TextField(null=True,blank=True,default=None)
    abx_lnz = models.TextField(null=True,blank=True,default=None)
    abx_lvx = models.TextField(null=True,blank=True,default=None)
    abx_mem = models.TextField(null=True,blank=True,default=None)
    abx_met = models.TextField(null=True,blank=True,default=None)
    abx_mfx = models.TextField(null=True,blank=True,default=None)
    abx_nal = models.TextField(null=True,blank=True,default=None)
    abx_nit = models.TextField(null=True,blank=True,default=None)
    abx_nor = models.TextField(null=True,blank=True,default=None)
    abx_ofx = models.TextField(null=True,blank=True,default=None)
    abx_oxa = models.TextField(null=True,blank=True,default=None)
    abx_pen = models.TextField(null=True,blank=True,default=None)
    abx_pip = models.TextField(null=True,blank=True,default=None)
    abx_rif = models.TextField(null=True,blank=True,default=None)
    abx_sam = models.TextField(null=True,blank=True,default=None)
    abx_spt = models.TextField(null=True,blank=True,default=None)
    abx_str = models.TextField(null=True,blank=True,default=None)
    abx_sxt = models.TextField(null=True,blank=True,default=None)
    abx_tcc = models.TextField(null=True,blank=True,default=None)
    abx_tcy = models.TextField(null=True,blank=True,default=None)
    abx_tec = models.TextField(null=True,blank=True,default=None)
    abx_tgc = models.TextField(null=True,blank=True,default=None)
    abx_tic = models.TextField(null=True,blank=True,default=None)
    abx_tob = models.TextField(null=True,blank=True,default=None)
    abx_tzd = models.TextField(null=True,blank=True,default=None)
    abx_tzp = models.TextField(null=True,blank=True,default=None)
    abx_van = models.TextField(null=True,blank=True,default=None)
    abx_xnl = models.TextField(null=True,blank=True,default=None)
    icr = models.TextField(null=True,blank=True,default=None)
    abx_amc_mic = models.TextField(null=True,blank=True,default=None)
    abx_amk_mic = models.TextField(null=True,blank=True,default=None)
    abx_amp_mic = models.TextField(null=True,blank=True,default=None)
    abx_atm_mic = models.TextField(null=True,blank=True,default=None)
    abx_azm_mic = models.TextField(null=True,blank=True,default=None)
    abx_caz_mic = models.TextField(null=True,blank=True,default=None)
    abx_cec_mic = models.TextField(null=True,blank=True,default=None)
    abx_cep_mic = models.TextField(null=True,blank=True,default=None)
    abx_cfm_mic = models.TextField(null=True,blank=True,default=None)
    abx_chl_mic = models.TextField(null=True,blank=True,default=None)
    abx_cip_mic = models.TextField(null=True,blank=True,default=None)
    abx_cli_mic = models.TextField(null=True,blank=True,default=None)
    abx_col_mic = models.TextField(null=True,blank=True,default=None)
    abx_cro_mic = models.TextField(null=True,blank=True,default=None)
    abx_csl_mic = models.TextField(null=True,blank=True,default=None)
    abx_ctx_mic = models.TextField(null=True,blank=True,default=None)
    abx_cxa_mic = models.TextField(null=True,blank=True,default=None)
    abx_cxm_mic = models.TextField(null=True,blank=True,default=None)
    abx_czo_mic = models.TextField(null=True,blank=True,default=None)
    abx_dap_mic = models.TextField(null=True,blank=True,default=None)
    abx_dor_mic = models.TextField(null=True,blank=True,default=None)
    abx_enr_mic = models.TextField(null=True,blank=True,default=None)
    abx_ery_mic = models.TextField(null=True,blank=True,default=None)
    abx_etp_mic = models.TextField(null=True,blank=True,default=None)
    abx_fep_mic = models.TextField(null=True,blank=True,default=None)
    abx_fox_mic = models.TextField(null=True,blank=True,default=None)
    abx_gen_mic = models.TextField(null=True,blank=True,default=None)
    abx_ipm_mic = models.TextField(null=True,blank=True,default=None)
    abx_lnz_mic = models.TextField(null=True,blank=True,default=None)
    abx_lvx_mic = models.TextField(null=True,blank=True,default=None)
    abx_mem_mic = models.TextField(null=True,blank=True,default=None)
    abx_met_mic = models.TextField(null=True,blank=True,default=None)
    abx_mfx_mic = models.TextField(null=True,blank=True,default=None)
    abx_nal_mic = models.TextField(null=True,blank=True,default=None)
    abx_nit_mic = models.TextField(null=True,blank=True,default=None)
    abx_nor_mic = models.TextField(null=True,blank=True,default=None)
    abx_ofx_mic = models.TextField(null=True,blank=True,default=None)
    abx_oxa_mic = models.TextField(null=True,blank=True,default=None)
    abx_pen_mic = models.TextField(null=True,blank=True,default=None)
    abx_pip_mic = models.TextField(null=True,blank=True,default=None)
    abx_rif_mic = models.TextField(null=True,blank=True,default=None)
    abx_sam_mic = models.TextField(null=True,blank=True,default=None)
    abx_spt_mic = models.TextField(null=True,blank=True,default=None)
    abx_str_mic = models.TextField(null=True,blank=True,default=None)
    abx_sxt_mic = models.TextField(null=True,blank=True,default=None)
    abx_tcc_mic = models.TextField(null=True,blank=True,default=None)
    abx_tcy_mic = models.TextField(null=True,blank=True,default=None)
    abx_tec_mic = models.TextField(null=True,blank=True,default=None)
    abx_tgc_mic = models.TextField(null=True,blank=True,default=None)
    abx_tic_mic = models.TextField(null=True,blank=True,default=None)
    abx_tob_mic = models.TextField(null=True,blank=True,default=None)
    abx_tzd_mic = models.TextField(null=True,blank=True,default=None)
    abx_tzp_mic = models.TextField(null=True,blank=True,default=None)
    abx_van_mic = models.TextField(null=True,blank=True,default=None)
    abx_xnl_mic = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.sample_id
    
    def get_all_data(self):
        queryset = self.__class__.objects.all()
        return queryset
    
    
class RetroQualifyr(models.Model):
    sample_name = models.TextField(null=True,blank=True,default=None,unique=True)
    result = models.TextField(null=True,blank=True,default=None)
    bactinspector_result_metric_value = models.TextField(null=True,blank=True,default=None)
    bactinspector_result_check_result = models.TextField(null=True,blank=True,default=None)
    bactinspector_species_metric_value = models.TextField(null=True,blank=True,default=None)
    bactinspector_species_check_result = models.TextField(null=True,blank=True,default=None)
    confindr_contam_status_metric_value = models.TextField(null=True,blank=True,default=None)
    confindr_contam_status_check_result = models.TextField(null=True,blank=True,default=None)
    confindr_percentage_contamination_metric_value = models.TextField(null=True,blank=True,default=None)
    confindr_percentage_contamination_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_adapter_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_adapter_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_basic_statistics_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_basic_statistics_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_overrepresented_sequences_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_overrepresented_sequences_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_base_n_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_base_n_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_base_sequence_quality_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_base_sequence_quality_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_sequence_gc_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_sequence_gc_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_sequence_quality_scores_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_per_sequence_quality_scores_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_sequence_duplication_levels_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_sequence_duplication_levels_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_1_sequence_length_distribution_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_1_sequence_length_distribution_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_adapter_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_adapter_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_basic_statistics_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_basic_statistics_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_overrepresented_sequences_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_overrepresented_sequences_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_base_n_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_base_n_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_base_sequence_quality_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_base_sequence_quality_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_sequence_gc_content_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_sequence_gc_content_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_sequence_quality_scores_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_per_sequence_quality_scores_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_sequence_duplication_levels_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_sequence_duplication_levels_check_result = models.TextField(null=True,blank=True,default=None)
    fastqc_2_sequence_length_distribution_metric_value = models.TextField(null=True,blank=True,default=None)
    fastqc_2_sequence_length_distribution_check_result = models.TextField(null=True,blank=True,default=None)
    file_size_check_size_metric_value = models.TextField(null=True,blank=True,default=None)
    file_size_check_size_check_result = models.TextField(null=True,blank=True,default=None)
    quast_contigs_1000_bp_metric_value = models.TextField(null=True,blank=True,default=None)
    quast_contigs_1000_bp_check_result = models.TextField(null=True,blank=True,default=None)
    quast_n50_metric_value = models.TextField(null=True,blank=True,default=None)
    quast_n50_check_result = models.TextField(null=True,blank=True,default=None)
    quast_total_length_1000_bp_metric_value = models.TextField(null=True,blank=True,default=None)
    quast_total_length_1000_bp_check_result = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class MlstSalmonella(models.Model):
    sample_id = models.TextField(null=True,blank=True,default=None,unique=True)
    sequence_type =  models.TextField(null=True,blank=True,default=None)
    hkg_aroc =  models.TextField(null=True,blank=True,default=None)
    hkg_dnan =  models.TextField(null=True,blank=True,default=None)
    hkg_hemd =  models.TextField(null=True,blank=True,default=None)
    hkg_hisd =  models.TextField(null=True,blank=True,default=None)
    hkg_pure =  models.TextField(null=True,blank=True,default=None)
    hkg_suca =  models.TextField(null=True,blank=True,default=None)
    hkg_thra =  models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)