from django.db import models

class RawFileName(models.Model):
    file_name = models.TextField(null=True,blank=True,default=None,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_name
    

class RawOrigin(models.Model):
    file_ref = models.ForeignKey(RawFileName, on_delete=models.CASCADE)
    country_a = models.TextField(null=True,blank=True,default=None)
    region = models.TextField(null=True,blank=True,default=None)
    island = models.TextField(null=True,blank=True,default=None)
    laboratory = models.TextField(null=True,blank=True,default=None)
    patient_id = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    mid_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_birth = models.TextField(null=True,blank=True,default=None)
    age_grp = models.TextField(null=True,blank=True,default=None)
    pat_type = models.TextField(null=True,blank=True,default=None)
    date_data = models.TextField(null=True,blank=True,default=None)
    x_referred = models.TextField(null=True,blank=True,default=None)
    x_recnum = models.TextField(null=True,blank=True,default=None)
    date_admis = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    stock_num = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_ref

class RawLocation(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    ward = models.TextField(null=True,blank=True,default=None)
    institut = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    ward_type = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ward



class RawMicrobiology(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    organism = models.TextField(null=True,blank=True,default=None)
    org_type = models.TextField(null=True,blank=True,default=None)
    beta_lact = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    induc_cli = models.TextField(null=True,blank=True,default=None)
    x_meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    x_mrse = models.TextField(null=True,blank=True,default=None)
    x_carb = models.TextField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    urine_count = models.TextField(null=True,blank=True,default=None)
    serotype = models.TextField(null=True,blank=True,default=None)
    carbapenem = models.TextField(null=True,blank=True,default=None)
    mbl = models.TextField(null=True,blank=True,default=None)
    growth = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organism
    

class RawSpecimen(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    spec_num = models.TextField(null=True,blank=True,default=None)
    spec_date = models.TextField(null=True,blank=True,default=None)
    spec_type = models.TextField(null=True,blank=True,default=None)
    spec_code = models.TextField(null=True,blank=True,default=None)
    local_spec = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.spec_type



class RawAntidisk(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30 = models.TextField(null=True,blank=True,default=None)
    amc_nd20 = models.TextField(null=True,blank=True,default=None)
    amp_nd10 = models.TextField(null=True,blank=True,default=None)
    sam_nd10 = models.TextField(null=True,blank=True,default=None)
    azm_nd15 = models.TextField(null=True,blank=True,default=None)
    atm_nd30 = models.TextField(null=True,blank=True,default=None)
    cec_nd30 = models.TextField(null=True,blank=True,default=None)
    man_nd30 = models.TextField(null=True,blank=True,default=None)
    czo_nd30 = models.TextField(null=True,blank=True,default=None)
    fep_nd30 = models.TextField(null=True,blank=True,default=None)
    cfm_nd5 = models.TextField(null=True,blank=True,default=None)
    cfp_nd75 = models.TextField(null=True,blank=True,default=None)
    ctx_nd30 = models.TextField(null=True,blank=True,default=None)
    fox_nd30 = models.TextField(null=True,blank=True,default=None)
    caz_nd30 = models.TextField(null=True,blank=True,default=None)
    cro_nd30 = models.TextField(null=True,blank=True,default=None)
    cxm_nd30 = models.TextField(null=True,blank=True,default=None)
    cxa_nd30 = models.TextField(null=True,blank=True,default=None)
    cep_nd30 = models.TextField(null=True,blank=True,default=None)
    chl_nd30 = models.TextField(null=True,blank=True,default=None)
    cip_nd5 = models.TextField(null=True,blank=True,default=None)
    clr_nd15 = models.TextField(null=True,blank=True,default=None)
    cli_nd2 = models.TextField(null=True,blank=True,default=None)
    col_nd10 = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2 = models.TextField(null=True,blank=True,default=None)
    dap_nd30 = models.TextField(null=True,blank=True,default=None)
    dor_nd10 = models.TextField(null=True,blank=True,default=None)
    etp_nd10 = models.TextField(null=True,blank=True,default=None)
    ery_nd15 = models.TextField(null=True,blank=True,default=None)
    gen_nd10 = models.TextField(null=True,blank=True,default=None)
    geh_nd120 = models.TextField(null=True,blank=True,default=None)
    ipm_nd10 = models.TextField(null=True,blank=True,default=None)
    kan_nd30 = models.TextField(null=True,blank=True,default=None)
    lvx_nd5 = models.TextField(null=True,blank=True,default=None)
    lnz_nd30 = models.TextField(null=True,blank=True,default=None)
    mem_nd10 = models.TextField(null=True,blank=True,default=None)
    mno_nd30 = models.TextField(null=True,blank=True,default=None)
    mfx_nd5 = models.TextField(null=True,blank=True,default=None)
    nal_nd30 = models.TextField(null=True,blank=True,default=None)
    net_nd30 = models.TextField(null=True,blank=True,default=None)
    nit_nd300 = models.TextField(null=True,blank=True,default=None)
    nor_nd10 = models.TextField(null=True,blank=True,default=None)
    nov_nd5 = models.TextField(null=True,blank=True,default=None)
    ofx_nd5 = models.TextField(null=True,blank=True,default=None)
    oxa_nd1 = models.TextField(null=True,blank=True,default=None)
    pen_nd10 = models.TextField(null=True,blank=True,default=None)
    pip_nd100 = models.TextField(null=True,blank=True,default=None)
    tzp_nd100 = models.TextField(null=True,blank=True,default=None)
    pol_nd300 = models.TextField(null=True,blank=True,default=None)
    qda_nd15 = models.TextField(null=True,blank=True,default=None)
    rif_nd5 = models.TextField(null=True,blank=True,default=None)
    spt_nd100 = models.TextField(null=True,blank=True,default=None)
    str_nd10 = models.TextField(null=True,blank=True,default=None)
    sth_nd300 = models.TextField(null=True,blank=True,default=None)
    tcy_nd30 = models.TextField(null=True,blank=True,default=None)
    tic_nd75 = models.TextField(null=True,blank=True,default=None)
    tcc_nd75 = models.TextField(null=True,blank=True,default=None)
    tgc_nd15 = models.TextField(null=True,blank=True,default=None)
    tob_nd10 = models.TextField(null=True,blank=True,default=None)
    van_nd30 = models.TextField(null=True,blank=True,default=None)
    fos_nd200 = models.TextField(null=True,blank=True,default=None)
    dox_nd30 = models.TextField(null=True,blank=True,default=None)
    sss_nd200 = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class RawAntimic(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm = models.TextField(null=True,blank=True,default=None)
    amc_nm = models.TextField(null=True,blank=True,default=None)
    amp_nm = models.TextField(null=True,blank=True,default=None)
    sam_nm = models.TextField(null=True,blank=True,default=None)
    azm_nm = models.TextField(null=True,blank=True,default=None)
    atm_nm = models.TextField(null=True,blank=True,default=None)
    cec_nm = models.TextField(null=True,blank=True,default=None)
    man_nm = models.TextField(null=True,blank=True,default=None)
    czo_nm = models.TextField(null=True,blank=True,default=None)
    fep_nm = models.TextField(null=True,blank=True,default=None)
    cfm_nm = models.TextField(null=True,blank=True,default=None)
    cfp_nm = models.TextField(null=True,blank=True,default=None)
    ctx_nm = models.TextField(null=True,blank=True,default=None)
    fox_nm = models.TextField(null=True,blank=True,default=None)
    caz_nm = models.TextField(null=True,blank=True,default=None)
    cro_nm = models.TextField(null=True,blank=True,default=None)
    cxm_nm = models.TextField(null=True,blank=True,default=None)
    cxa_nm = models.TextField(null=True,blank=True,default=None)
    cep_nm = models.TextField(null=True,blank=True,default=None)
    chl_nm = models.TextField(null=True,blank=True,default=None)
    cip_nm = models.TextField(null=True,blank=True,default=None)
    clr_nm = models.TextField(null=True,blank=True,default=None)
    cli_nm = models.TextField(null=True,blank=True,default=None)
    col_nm = models.TextField(null=True,blank=True,default=None)
    sxt_nm = models.TextField(null=True,blank=True,default=None)
    dap_nm = models.TextField(null=True,blank=True,default=None)
    dor_nm = models.TextField(null=True,blank=True,default=None)
    etp_nm = models.TextField(null=True,blank=True,default=None)
    ery_nm = models.TextField(null=True,blank=True,default=None)
    gen_nm = models.TextField(null=True,blank=True,default=None)
    geh_nm = models.TextField(null=True,blank=True,default=None)
    ipm_nm = models.TextField(null=True,blank=True,default=None)
    kan_nm = models.TextField(null=True,blank=True,default=None)
    lvx_nm = models.TextField(null=True,blank=True,default=None)
    lnz_nm = models.TextField(null=True,blank=True,default=None)
    mem_nm = models.TextField(null=True,blank=True,default=None)
    mno_nm = models.TextField(null=True,blank=True,default=None)
    mfx_nm = models.TextField(null=True,blank=True,default=None)
    nal_nm = models.TextField(null=True,blank=True,default=None)
    net_nm = models.TextField(null=True,blank=True,default=None)
    nit_nm = models.TextField(null=True,blank=True,default=None)
    nor_nm = models.TextField(null=True,blank=True,default=None)
    nov_nm = models.TextField(null=True,blank=True,default=None)
    ofx_nm = models.TextField(null=True,blank=True,default=None)
    oxa_nm = models.TextField(null=True,blank=True,default=None)
    pen_nm = models.TextField(null=True,blank=True,default=None)
    pip_nm = models.TextField(null=True,blank=True,default=None)
    tzp_nm = models.TextField(null=True,blank=True,default=None)
    pol_nm = models.TextField(null=True,blank=True,default=None)
    qda_nm = models.TextField(null=True,blank=True,default=None)
    rif_nm = models.TextField(null=True,blank=True,default=None)
    spt_nm = models.TextField(null=True,blank=True,default=None)
    str_nm = models.TextField(null=True,blank=True,default=None)
    sth_nm = models.TextField(null=True,blank=True,default=None)
    tcy_nm = models.TextField(null=True,blank=True,default=None)
    tic_nm = models.TextField(null=True,blank=True,default=None)
    tcc_nm = models.TextField(null=True,blank=True,default=None)
    tgc_nm = models.TextField(null=True,blank=True,default=None)
    tob_nm = models.TextField(null=True,blank=True,default=None)
    van_nm = models.TextField(null=True,blank=True,default=None)
    fos_nm = models.TextField(null=True,blank=True,default=None)
    dox_nm = models.TextField(null=True,blank=True,default=None)
    sss_nm = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref


class RawAntietest(models.Model):
    origin_ref = models.OneToOneField(RawOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_ne = models.TextField(null=True,blank=True,default=None)
    amc_ne = models.TextField(null=True,blank=True,default=None)
    amp_ne = models.TextField(null=True,blank=True,default=None)
    sam_ne = models.TextField(null=True,blank=True,default=None)
    azm_ne = models.TextField(null=True,blank=True,default=None)
    atm_ne = models.TextField(null=True,blank=True,default=None)
    cec_ne = models.TextField(null=True,blank=True,default=None)
    man_ne = models.TextField(null=True,blank=True,default=None)
    czo_ne = models.TextField(null=True,blank=True,default=None)
    fep_ne = models.TextField(null=True,blank=True,default=None)
    cfm_ne = models.TextField(null=True,blank=True,default=None)
    cfp_ne = models.TextField(null=True,blank=True,default=None)
    ctx_ne = models.TextField(null=True,blank=True,default=None)
    fox_ne = models.TextField(null=True,blank=True,default=None)
    caz_ne = models.TextField(null=True,blank=True,default=None)
    cro_ne = models.TextField(null=True,blank=True,default=None)
    cxm_ne = models.TextField(null=True,blank=True,default=None)
    cxa_ne = models.TextField(null=True,blank=True,default=None)
    cep_ne = models.TextField(null=True,blank=True,default=None)
    chl_ne = models.TextField(null=True,blank=True,default=None)
    cip_ne = models.TextField(null=True,blank=True,default=None)
    clr_ne = models.TextField(null=True,blank=True,default=None)
    cli_ne = models.TextField(null=True,blank=True,default=None)
    col_ne = models.TextField(null=True,blank=True,default=None)
    sxt_ne = models.TextField(null=True,blank=True,default=None)
    dap_ne = models.TextField(null=True,blank=True,default=None)
    dor_ne = models.TextField(null=True,blank=True,default=None)
    etp_ne = models.TextField(null=True,blank=True,default=None)
    ery_ne = models.TextField(null=True,blank=True,default=None)
    gen_ne = models.TextField(null=True,blank=True,default=None)
    geh_ne = models.TextField(null=True,blank=True,default=None)
    ipm_ne = models.TextField(null=True,blank=True,default=None)
    kan_ne = models.TextField(null=True,blank=True,default=None)
    lvx_ne = models.TextField(null=True,blank=True,default=None)
    lnz_ne = models.TextField(null=True,blank=True,default=None)
    mem_ne = models.TextField(null=True,blank=True,default=None)
    mno_ne = models.TextField(null=True,blank=True,default=None)
    mfx_ne = models.TextField(null=True,blank=True,default=None)
    nal_ne = models.TextField(null=True,blank=True,default=None)
    net_ne = models.TextField(null=True,blank=True,default=None)
    nit_ne = models.TextField(null=True,blank=True,default=None)
    nor_ne = models.TextField(null=True,blank=True,default=None)
    nov_ne = models.TextField(null=True,blank=True,default=None)
    ofx_ne = models.TextField(null=True,blank=True,default=None)
    oxa_ne = models.TextField(null=True,blank=True,default=None)
    pen_ne = models.TextField(null=True,blank=True,default=None)
    pip_ne = models.TextField(null=True,blank=True,default=None)
    tzp_ne = models.TextField(null=True,blank=True,default=None)
    pol_ne = models.TextField(null=True,blank=True,default=None)
    qda_ne = models.TextField(null=True,blank=True,default=None)
    rif_ne = models.TextField(null=True,blank=True,default=None)
    spt_ne = models.TextField(null=True,blank=True,default=None)
    str_ne = models.TextField(null=True,blank=True,default=None)
    sth_ne = models.TextField(null=True,blank=True,default=None)
    tcy_ne = models.TextField(null=True,blank=True,default=None)
    tic_ne = models.TextField(null=True,blank=True,default=None)
    tcc_ne = models.TextField(null=True,blank=True,default=None)
    tgc_ne = models.TextField(null=True,blank=True,default=None)
    tob_ne = models.TextField(null=True,blank=True,default=None)
    van_ne = models.TextField(null=True,blank=True,default=None)
    fos_ne = models.TextField(null=True,blank=True,default=None)
    dox_ne = models.TextField(null=True,blank=True,default=None)
    sss_ne = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    
    
    

#OLD REFERRED DATA DITO ANG START


class OldFileName(models.Model):
    file_name = models.TextField(null=True,blank=True,default=None,unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_name
    

class OldOrigin(models.Model):
    file_ref = models.ForeignKey(OldFileName, on_delete=models.CASCADE)
    country_a = models.TextField(null=True,blank=True,default=None)
    region = models.TextField(null=True,blank=True,default=None)
    island = models.TextField(null=True,blank=True,default=None)
    laboratory = models.TextField(null=True,blank=True,default=None)
    patient_id = models.TextField(null=True,blank=True,default=None)
    first_name = models.TextField(null=True,blank=True,default=None)
    mid_name = models.TextField(null=True,blank=True,default=None)
    last_name = models.TextField(null=True,blank=True,default=None)
    sex = models.TextField(null=True,blank=True,default=None)
    age = models.TextField(null=True,blank=True,default=None)
    date_birth = models.TextField(null=True,blank=True,default=None)
    age_grp = models.TextField(null=True,blank=True,default=None)
    pat_type = models.TextField(null=True,blank=True,default=None)
    date_data = models.TextField(null=True,blank=True,default=None)
    x_referred = models.TextField(null=True,blank=True,default=None)
    x_recnum = models.TextField(null=True,blank=True,default=None)
    date_admis = models.TextField(null=True,blank=True,default=None)
    nosocomial = models.TextField(null=True,blank=True,default=None)
    diagnosis = models.TextField(null=True,blank=True,default=None)
    stock_num = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file_ref

class OldLocation(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    ward = models.TextField(null=True,blank=True,default=None)
    institut = models.TextField(null=True,blank=True,default=None)
    department = models.TextField(null=True,blank=True,default=None)
    ward_type = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ward



class OldMicrobiology(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    organism = models.TextField(null=True,blank=True,default=None)
    org_type = models.TextField(null=True,blank=True,default=None)
    beta_lact = models.TextField(null=True,blank=True,default=None)
    comment = models.TextField(null=True,blank=True,default=None)
    mrsa = models.TextField(null=True,blank=True,default=None)
    induc_cli = models.TextField(null=True,blank=True,default=None)
    x_meca = models.TextField(null=True,blank=True,default=None)
    ampc = models.TextField(null=True,blank=True,default=None)
    x_mrse = models.TextField(null=True,blank=True,default=None)
    x_carb = models.TextField(null=True,blank=True,default=None)
    esbl = models.TextField(null=True,blank=True,default=None)
    urine_count = models.TextField(null=True,blank=True,default=None)
    serotype = models.TextField(null=True,blank=True,default=None)
    carbapenem = models.TextField(null=True,blank=True,default=None)
    mbl = models.TextField(null=True,blank=True,default=None)
    growth = models.TextField(null=True,blank=True,default=None)
    arsrl_pre = models.TextField(null=True,blank=True,default=None)
    arsrl_final = models.TextField(null=True,blank=True,default=None)
    arsrl_post = models.TextField(null=True,blank=True,default=None)
    x_esbl_ct = models.TextField(null=True,blank=True,default=None)
    x_esbl_tz = models.TextField(null=True,blank=True,default=None)
    x_ip_ipi = models.TextField(null=True,blank=True,default=None)
    x_cn_cni = models.TextField(null=True,blank=True,default=None)
    edta = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organism
    

class OldSpecimen(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    spec_num = models.TextField(null=True,blank=True,default=None)
    spec_date = models.TextField(null=True,blank=True,default=None)
    spec_type = models.TextField(null=True,blank=True,default=None)
    spec_code = models.TextField(null=True,blank=True,default=None)
    local_spec = models.TextField(null=True,blank=True,default=None)
    date_refer = models.TextField(null=True,blank=True,default=None)
    reason = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.spec_type



class OldAntidisk(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30 = models.TextField(null=True,blank=True,default=None)
    amc_nd20 = models.TextField(null=True,blank=True,default=None)
    amp_nd10 = models.TextField(null=True,blank=True,default=None)
    sam_nd10 = models.TextField(null=True,blank=True,default=None)
    azm_nd15 = models.TextField(null=True,blank=True,default=None)
    atm_nd30 = models.TextField(null=True,blank=True,default=None)
    cec_nd30 = models.TextField(null=True,blank=True,default=None)
    man_nd30 = models.TextField(null=True,blank=True,default=None)
    czo_nd30 = models.TextField(null=True,blank=True,default=None)
    fep_nd30 = models.TextField(null=True,blank=True,default=None)
    cfm_nd5 = models.TextField(null=True,blank=True,default=None)
    cfp_nd75 = models.TextField(null=True,blank=True,default=None)
    ctx_nd30 = models.TextField(null=True,blank=True,default=None)
    fox_nd30 = models.TextField(null=True,blank=True,default=None)
    caz_nd30 = models.TextField(null=True,blank=True,default=None)
    cro_nd30 = models.TextField(null=True,blank=True,default=None)
    cxm_nd30 = models.TextField(null=True,blank=True,default=None)
    cxa_nd30 = models.TextField(null=True,blank=True,default=None)
    cep_nd30 = models.TextField(null=True,blank=True,default=None)
    chl_nd30 = models.TextField(null=True,blank=True,default=None)
    cip_nd5 = models.TextField(null=True,blank=True,default=None)
    clr_nd15 = models.TextField(null=True,blank=True,default=None)
    cli_nd2 = models.TextField(null=True,blank=True,default=None)
    col_nd10 = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2 = models.TextField(null=True,blank=True,default=None)
    dap_nd30 = models.TextField(null=True,blank=True,default=None)
    dor_nd10 = models.TextField(null=True,blank=True,default=None)
    etp_nd10 = models.TextField(null=True,blank=True,default=None)
    ery_nd15 = models.TextField(null=True,blank=True,default=None)
    gen_nd10 = models.TextField(null=True,blank=True,default=None)
    geh_nd120 = models.TextField(null=True,blank=True,default=None)
    ipm_nd10 = models.TextField(null=True,blank=True,default=None)
    kan_nd30 = models.TextField(null=True,blank=True,default=None)
    lvx_nd5 = models.TextField(null=True,blank=True,default=None)
    lnz_nd30 = models.TextField(null=True,blank=True,default=None)
    mem_nd10 = models.TextField(null=True,blank=True,default=None)
    mno_nd30 = models.TextField(null=True,blank=True,default=None)
    mfx_nd5 = models.TextField(null=True,blank=True,default=None)
    nal_nd30 = models.TextField(null=True,blank=True,default=None)
    net_nd30 = models.TextField(null=True,blank=True,default=None)
    nit_nd300 = models.TextField(null=True,blank=True,default=None)
    nor_nd10 = models.TextField(null=True,blank=True,default=None)
    nov_nd5 = models.TextField(null=True,blank=True,default=None)
    ofx_nd5 = models.TextField(null=True,blank=True,default=None)
    oxa_nd1 = models.TextField(null=True,blank=True,default=None)
    pen_nd10 = models.TextField(null=True,blank=True,default=None)
    pip_nd100 = models.TextField(null=True,blank=True,default=None)
    tzp_nd100 = models.TextField(null=True,blank=True,default=None)
    pol_nd300 = models.TextField(null=True,blank=True,default=None)
    qda_nd15 = models.TextField(null=True,blank=True,default=None)
    rif_nd5 = models.TextField(null=True,blank=True,default=None)
    spt_nd100 = models.TextField(null=True,blank=True,default=None)
    str_nd10 = models.TextField(null=True,blank=True,default=None)
    sth_nd300 = models.TextField(null=True,blank=True,default=None)
    tcy_nd30 = models.TextField(null=True,blank=True,default=None)
    tic_nd75 = models.TextField(null=True,blank=True,default=None)
    tcc_nd75 = models.TextField(null=True,blank=True,default=None)
    tgc_nd15 = models.TextField(null=True,blank=True,default=None)
    tob_nd10 = models.TextField(null=True,blank=True,default=None)
    van_nd30 = models.TextField(null=True,blank=True,default=None)
    fos_nd200 = models.TextField(null=True,blank=True,default=None)
    dox_nd30 = models.TextField(null=True,blank=True,default=None)
    sss_nd200 = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class OldAntimic(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm = models.TextField(null=True,blank=True,default=None)
    amc_nm = models.TextField(null=True,blank=True,default=None)
    amp_nm = models.TextField(null=True,blank=True,default=None)
    sam_nm = models.TextField(null=True,blank=True,default=None)
    azm_nm = models.TextField(null=True,blank=True,default=None)
    atm_nm = models.TextField(null=True,blank=True,default=None)
    cec_nm = models.TextField(null=True,blank=True,default=None)
    man_nm = models.TextField(null=True,blank=True,default=None)
    czo_nm = models.TextField(null=True,blank=True,default=None)
    fep_nm = models.TextField(null=True,blank=True,default=None)
    cfm_nm = models.TextField(null=True,blank=True,default=None)
    cfp_nm = models.TextField(null=True,blank=True,default=None)
    ctx_nm = models.TextField(null=True,blank=True,default=None)
    fox_nm = models.TextField(null=True,blank=True,default=None)
    caz_nm = models.TextField(null=True,blank=True,default=None)
    cro_nm = models.TextField(null=True,blank=True,default=None)
    cxm_nm = models.TextField(null=True,blank=True,default=None)
    cxa_nm = models.TextField(null=True,blank=True,default=None)
    cep_nm = models.TextField(null=True,blank=True,default=None)
    chl_nm = models.TextField(null=True,blank=True,default=None)
    cip_nm = models.TextField(null=True,blank=True,default=None)
    clr_nm = models.TextField(null=True,blank=True,default=None)
    cli_nm = models.TextField(null=True,blank=True,default=None)
    col_nm = models.TextField(null=True,blank=True,default=None)
    sxt_nm = models.TextField(null=True,blank=True,default=None)
    dap_nm = models.TextField(null=True,blank=True,default=None)
    dor_nm = models.TextField(null=True,blank=True,default=None)
    etp_nm = models.TextField(null=True,blank=True,default=None)
    ery_nm = models.TextField(null=True,blank=True,default=None)
    gen_nm = models.TextField(null=True,blank=True,default=None)
    geh_nm = models.TextField(null=True,blank=True,default=None)
    ipm_nm = models.TextField(null=True,blank=True,default=None)
    kan_nm = models.TextField(null=True,blank=True,default=None)
    lvx_nm = models.TextField(null=True,blank=True,default=None)
    lnz_nm = models.TextField(null=True,blank=True,default=None)
    mem_nm = models.TextField(null=True,blank=True,default=None)
    mno_nm = models.TextField(null=True,blank=True,default=None)
    mfx_nm = models.TextField(null=True,blank=True,default=None)
    nal_nm = models.TextField(null=True,blank=True,default=None)
    net_nm = models.TextField(null=True,blank=True,default=None)
    nit_nm = models.TextField(null=True,blank=True,default=None)
    nor_nm = models.TextField(null=True,blank=True,default=None)
    nov_nm = models.TextField(null=True,blank=True,default=None)
    ofx_nm = models.TextField(null=True,blank=True,default=None)
    oxa_nm = models.TextField(null=True,blank=True,default=None)
    pen_nm = models.TextField(null=True,blank=True,default=None)
    pip_nm = models.TextField(null=True,blank=True,default=None)
    tzp_nm = models.TextField(null=True,blank=True,default=None)
    pol_nm = models.TextField(null=True,blank=True,default=None)
    qda_nm = models.TextField(null=True,blank=True,default=None)
    rif_nm = models.TextField(null=True,blank=True,default=None)
    spt_nm = models.TextField(null=True,blank=True,default=None)
    str_nm = models.TextField(null=True,blank=True,default=None)
    sth_nm = models.TextField(null=True,blank=True,default=None)
    tcy_nm = models.TextField(null=True,blank=True,default=None)
    tic_nm = models.TextField(null=True,blank=True,default=None)
    tcc_nm = models.TextField(null=True,blank=True,default=None)
    tgc_nm = models.TextField(null=True,blank=True,default=None)
    tob_nm = models.TextField(null=True,blank=True,default=None)
    van_nm = models.TextField(null=True,blank=True,default=None)
    fos_nm = models.TextField(null=True,blank=True,default=None)
    dox_nm = models.TextField(null=True,blank=True,default=None)
    sss_nm = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref


class OldAntidiskris(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nd30_ris = models.TextField(null=True,blank=True,default=None)
    amc_nd20_ris = models.TextField(null=True,blank=True,default=None)
    amp_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sam_nd10_ris = models.TextField(null=True,blank=True,default=None)
    azm_nd15_ris = models.TextField(null=True,blank=True,default=None)
    atm_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cec_nd30_ris = models.TextField(null=True,blank=True,default=None)
    man_nd30_ris = models.TextField(null=True,blank=True,default=None)
    czo_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fep_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cfm_nd5_ris = models.TextField(null=True,blank=True,default=None)
    cfp_nd75_ris = models.TextField(null=True,blank=True,default=None)
    ctx_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fox_nd30_ris = models.TextField(null=True,blank=True,default=None)
    caz_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cro_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cxm_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cxa_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cep_nd30_ris = models.TextField(null=True,blank=True,default=None)
    chl_nd30_ris = models.TextField(null=True,blank=True,default=None)
    cip_nd5_ris = models.TextField(null=True,blank=True,default=None)
    clr_nd15_ris = models.TextField(null=True,blank=True,default=None)
    cli_nd2_ris = models.TextField(null=True,blank=True,default=None)
    col_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sxt_nd1_2_ris = models.TextField(null=True,blank=True,default=None)
    dap_nd30_ris = models.TextField(null=True,blank=True,default=None)
    dor_nd10_ris = models.TextField(null=True,blank=True,default=None)
    etp_nd10_ris = models.TextField(null=True,blank=True,default=None)
    ery_nd15_ris = models.TextField(null=True,blank=True,default=None)
    gen_nd10_ris = models.TextField(null=True,blank=True,default=None)
    geh_nd120_ris = models.TextField(null=True,blank=True,default=None)
    ipm_nd10_ris = models.TextField(null=True,blank=True,default=None)
    kan_nd30_ris = models.TextField(null=True,blank=True,default=None)
    lvx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    lnz_nd30_ris = models.TextField(null=True,blank=True,default=None)
    mem_nd10_ris = models.TextField(null=True,blank=True,default=None)
    mno_nd30_ris = models.TextField(null=True,blank=True,default=None)
    mfx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    nal_nd30_ris = models.TextField(null=True,blank=True,default=None)
    net_nd30_ris = models.TextField(null=True,blank=True,default=None)
    nit_nd300_ris = models.TextField(null=True,blank=True,default=None)
    nor_nd10_ris = models.TextField(null=True,blank=True,default=None)
    nov_nd5_ris = models.TextField(null=True,blank=True,default=None)
    ofx_nd5_ris = models.TextField(null=True,blank=True,default=None)
    oxa_nd1_ris = models.TextField(null=True,blank=True,default=None)
    pen_nd10_ris = models.TextField(null=True,blank=True,default=None)
    pip_nd100_ris = models.TextField(null=True,blank=True,default=None)
    tzp_nd100_ris = models.TextField(null=True,blank=True,default=None)
    pol_nd300_ris = models.TextField(null=True,blank=True,default=None)
    qda_nd15_ris = models.TextField(null=True,blank=True,default=None)
    rif_nd5_ris = models.TextField(null=True,blank=True,default=None)
    spt_nd100_ris = models.TextField(null=True,blank=True,default=None)
    str_nd10_ris = models.TextField(null=True,blank=True,default=None)
    sth_nd300_ris = models.TextField(null=True,blank=True,default=None)
    tcy_nd30_ris = models.TextField(null=True,blank=True,default=None)
    tic_nd75_ris = models.TextField(null=True,blank=True,default=None)
    tcc_nd75_ris = models.TextField(null=True,blank=True,default=None)
    tgc_nd15_ris = models.TextField(null=True,blank=True,default=None)
    tob_nd10_ris = models.TextField(null=True,blank=True,default=None)
    van_nd30_ris = models.TextField(null=True,blank=True,default=None)
    fos_nd200_ris = models.TextField(null=True,blank=True,default=None)
    dox_nd30_ris = models.TextField(null=True,blank=True,default=None)
    sss_nd200_ris = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    

class OldAntimicris(models.Model):
    origin_ref = models.OneToOneField(OldOrigin,  on_delete = models.CASCADE, primary_key = True) 
    amk_nm_ris = models.TextField(null=True,blank=True,default=None)
    amc_nm_ris = models.TextField(null=True,blank=True,default=None)
    amp_nm_ris = models.TextField(null=True,blank=True,default=None)
    sam_nm_ris = models.TextField(null=True,blank=True,default=None)
    azm_nm_ris = models.TextField(null=True,blank=True,default=None)
    atm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cec_nm_ris = models.TextField(null=True,blank=True,default=None)
    man_nm_ris = models.TextField(null=True,blank=True,default=None)
    czo_nm_ris = models.TextField(null=True,blank=True,default=None)
    fep_nm_ris = models.TextField(null=True,blank=True,default=None)
    cfm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cfp_nm_ris = models.TextField(null=True,blank=True,default=None)
    ctx_nm_ris = models.TextField(null=True,blank=True,default=None)
    fox_nm_ris = models.TextField(null=True,blank=True,default=None)
    caz_nm_ris = models.TextField(null=True,blank=True,default=None)
    cro_nm_ris = models.TextField(null=True,blank=True,default=None)
    cxm_nm_ris = models.TextField(null=True,blank=True,default=None)
    cxa_nm_ris = models.TextField(null=True,blank=True,default=None)
    cep_nm_ris = models.TextField(null=True,blank=True,default=None)
    chl_nm_ris = models.TextField(null=True,blank=True,default=None)
    cip_nm_ris = models.TextField(null=True,blank=True,default=None)
    clr_nm_ris = models.TextField(null=True,blank=True,default=None)
    cli_nm_ris = models.TextField(null=True,blank=True,default=None)
    col_nm_ris = models.TextField(null=True,blank=True,default=None)
    sxt_nm_ris = models.TextField(null=True,blank=True,default=None)
    dap_nm_ris = models.TextField(null=True,blank=True,default=None)
    dor_nm_ris = models.TextField(null=True,blank=True,default=None)
    etp_nm_ris = models.TextField(null=True,blank=True,default=None)
    ery_nm_ris = models.TextField(null=True,blank=True,default=None)
    gen_nm_ris = models.TextField(null=True,blank=True,default=None)
    geh_nm_ris = models.TextField(null=True,blank=True,default=None)
    ipm_nm_ris = models.TextField(null=True,blank=True,default=None)
    kan_nm_ris = models.TextField(null=True,blank=True,default=None)
    lvx_nm_ris = models.TextField(null=True,blank=True,default=None)
    lnz_nm_ris = models.TextField(null=True,blank=True,default=None)
    mem_nm_ris = models.TextField(null=True,blank=True,default=None)
    mno_nm_ris = models.TextField(null=True,blank=True,default=None)
    mfx_nm_ris = models.TextField(null=True,blank=True,default=None)
    nal_nm_ris = models.TextField(null=True,blank=True,default=None)
    net_nm_ris = models.TextField(null=True,blank=True,default=None)
    nit_nm_ris = models.TextField(null=True,blank=True,default=None)
    nor_nm_ris = models.TextField(null=True,blank=True,default=None)
    nov_nm_ris = models.TextField(null=True,blank=True,default=None)
    ofx_nm_ris = models.TextField(null=True,blank=True,default=None)
    oxa_nm_ris = models.TextField(null=True,blank=True,default=None)
    pen_nm_ris = models.TextField(null=True,blank=True,default=None)
    pip_nm_ris = models.TextField(null=True,blank=True,default=None)
    tzp_nm_ris = models.TextField(null=True,blank=True,default=None)
    pol_nm_ris = models.TextField(null=True,blank=True,default=None)
    qda_nm_ris = models.TextField(null=True,blank=True,default=None)
    rif_nm_ris = models.TextField(null=True,blank=True,default=None)
    spt_nm_ris = models.TextField(null=True,blank=True,default=None)
    str_nm_ris = models.TextField(null=True,blank=True,default=None)
    sth_nm_ris = models.TextField(null=True,blank=True,default=None)
    tcy_nm_ris = models.TextField(null=True,blank=True,default=None)
    tic_nm_ris = models.TextField(null=True,blank=True,default=None)
    tcc_nm_ris = models.TextField(null=True,blank=True,default=None)
    tgc_nm_ris = models.TextField(null=True,blank=True,default=None)
    tob_nm_ris = models.TextField(null=True,blank=True,default=None)
    van_nm_ris = models.TextField(null=True,blank=True,default=None)
    fos_nm_ris = models.TextField(null=True,blank=True,default=None)
    dox_nm_ris = models.TextField(null=True,blank=True,default=None)
    sss_nm_ris = models.TextField(null=True,blank=True,default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.origin_ref
    
    
    