# Generated by Django 3.0.3 on 2021-03-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referredmicrobiology',
            name='x_carb',
        ),
    ]
