# Generated by Django 3.0.2 on 2020-02-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawspecimen',
            name='local_spec',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
