# Generated by Django 3.0.2 on 2020-02-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmicrobiology',
            old_name='meca',
            new_name='x_meca',
        ),
    ]
