# Generated by Django 3.0.2 on 2020-03-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0002_oldantidisk_oldantidiskris_oldantimic_oldantimicris_oldfilename_oldlocation_oldmicrobiology_oldorigi'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldspecimen',
            name='date_refer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oldspecimen',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
