# Generated by Django 3.0.2 on 2020-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0002_rawspecimen_local_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawantidisk',
            name='fos_nd200',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantimic',
            name='fos_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
