# Generated by Django 3.0.2 on 2020-02-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0003_auto_20200218_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawantidisk',
            name='dox_nd30',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantidisk',
            name='sss_nd200',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantimic',
            name='dox_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantimic',
            name='sss_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
