# Generated by Django 3.0.3 on 2021-11-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0004_auto_20211103_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpiMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('alternative_sample_id', models.TextField(blank=True, default=None, null=True)),
                ('ghru_uuid', models.TextField(blank=True, default=None, null=True)),
                ('species', models.TextField(blank=True, default=None, null=True)),
                ('wgs_id', models.TextField(blank=True, default=None, null=True)),
                ('wgs_qc', models.TextField(blank=True, default=None, null=True)),
                ('country', models.TextField(blank=True, default=None, null=True)),
                ('country_alpha_2_code', models.TextField(blank=True, default=None, null=True)),
                ('region_province_department', models.TextField(blank=True, default=None, null=True)),
                ('iso_3166_2_subdivision_code', models.TextField(blank=True, default=None, null=True)),
                ('location', models.TextField(blank=True, default=None, null=True)),
                ('sentinel_site_code', models.TextField(blank=True, default=None, null=True)),
                ('latitude', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.TextField(blank=True, default=None, null=True)),
                ('collected_by', models.TextField(blank=True, default=None, null=True)),
                ('collection_contact', models.TextField(blank=True, default=None, null=True)),
                ('collection_date', models.TextField(blank=True, default=None, null=True)),
                ('year', models.TextField(blank=True, default=None, null=True)),
                ('month', models.TextField(blank=True, default=None, null=True)),
                ('day', models.TextField(blank=True, default=None, null=True)),
                ('outbreak_isolate', models.TextField(blank=True, default=None, null=True)),
                ('clinical_significance', models.TextField(blank=True, default=None, null=True)),
                ('host', models.TextField(blank=True, default=None, null=True)),
                ('specimen_type', models.TextField(blank=True, default=None, null=True)),
                ('invasive', models.TextField(blank=True, default=None, null=True)),
                ('patient_type', models.TextField(blank=True, default=None, null=True)),
                ('ward_inpatients_only', models.TextField(blank=True, default=None, null=True)),
                ('room_inpatients_only', models.TextField(blank=True, default=None, null=True)),
                ('address_outpatients_only', models.TextField(blank=True, default=None, null=True)),
                ('address_latitude_outpatients_only', models.TextField(blank=True, default=None, null=True)),
                ('address_longitude_outpatients_only', models.TextField(blank=True, default=None, null=True)),
                ('origin', models.TextField(blank=True, default=None, null=True)),
                ('hai_type', models.TextField(blank=True, default=None, null=True)),
                ('patient_date_of_birth', models.TextField(blank=True, default=None, null=True)),
                ('patient_age', models.TextField(blank=True, default=None, null=True)),
                ('patient_gender', models.TextField(blank=True, default=None, null=True)),
                ('clinical_diagnosis', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GhruQualifyr',
        ),
    ]
