# Generated by Django 3.0.3 on 2021-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0005_auto_20211118_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amc_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amk',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amk_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_amp_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_atm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_atm_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_azm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_azm_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_caz',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_caz_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cec',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cec_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cep',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cep_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cfm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cfm_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_chl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_chl_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cip_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cli',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cli_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_col',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_col_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cro',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cro_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_csl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_csl_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ctx',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ctx_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cxa',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cxa_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cxm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_cxm_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_czo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_czo_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_dap',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_dap_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_dor',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_dor_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_enr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_enr_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ery',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ery_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_etp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_etp_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_fep',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_fep_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_fox',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_fox_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_gen',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_gen_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ipm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ipm_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_lnz',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_lnz_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_lvx',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_lvx_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_mem',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_mem_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_met',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_met_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_mfx',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_mfx_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nal',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nal_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nit',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nit_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nor',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_nor_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ofx',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_ofx_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_oxa',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_oxa_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_pen',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_pen_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_pip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_pip_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_rif',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_rif_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_sam',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_sam_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_spt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_spt_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_str',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_str_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_sxt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_sxt_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tcc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tcc_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tcy',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tcy_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tec',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tec_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tgc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tgc_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tic_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tob',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tob_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tzd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tzd_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tzp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_tzp_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_van',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_van_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_xnl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='abx_xnl_mic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='ast_profile',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='card_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='icr',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='instrument',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='epimetadata',
            name='submitted_as',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
