# Generated by Django 3.0.3 on 2021-11-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0007_retroqualifyr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlstSalmonella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('sequence_type', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_aroc', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_dnan', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_hemd', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_hisd', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_pure', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_suca', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('hkg_thra', models.TextField(blank=True, default=None, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
