# Generated by Django 3.0.3 on 2021-11-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0008_mlstsalmonella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_aroc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_dnan',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_hemd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_hisd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_pure',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_suca',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='hkg_thra',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mlstsalmonella',
            name='sequence_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
