# Generated by Django 3.0.3 on 2023-10-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whonet', '0012_auto_20231016_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalantidisk',
            name='tzd_nd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='finalantietest',
            name='tzd_ne',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='finalantimic',
            name='tzd_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantidisk',
            name='tzd_nd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantietest',
            name='tzd_ne',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rawantimic',
            name='tzd_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='referredantidisk',
            name='tzd_nd',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='referredantidiskris',
            name='tzd_nd_ris',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='referredantimic',
            name='tzd_nm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='referredantimicris',
            name='tzd_nm_ris',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
